# coding: utf-8

"""
    Twenty Api

    Twenty is a customer relationship management (CRM) platform designed to help businesses manage their customer interactions and relationships effectively. The Twenty API provides programmatic access to the features and functionalities of the Twenty CRM platform, allowing developers to integrate and interact with the CRM data and operations.

    The version of the OpenAPI document: v0.1
    Contact: felix@twenty.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from twentycrm_client.models.person_linkedin_link import PersonLinkedinLink

class TestPersonLinkedinLink(unittest.TestCase):
    """PersonLinkedinLink unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PersonLinkedinLink:
        """Test PersonLinkedinLink
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PersonLinkedinLink`
        """
        model = PersonLinkedinLink()
        if include_optional:
            return PersonLinkedinLink(
                primary_link_label = '',
                primary_link_url = '',
                secondary_links = [
                    twentycrm_client.models.calendar_event_conference_link_secondary_links_inner.CalendarEvent_conferenceLink_secondaryLinks_inner(
                        url = '', 
                        label = '', )
                    ]
            )
        else:
            return PersonLinkedinLink(
        )
        """

    def testPersonLinkedinLink(self):
        """Test PersonLinkedinLink"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
