# coding: utf-8

"""
    Twenty Api

    Twenty is a customer relationship management (CRM) platform designed to help businesses manage their customer interactions and relationships effectively. The Twenty API provides programmatic access to the features and functionalities of the Twenty CRM platform, allowing developers to integrate and interact with the CRM data and operations.

    The version of the OpenAPI document: v0.1
    Contact: felix@twenty.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from twentycrm_client.api.calendar_channel_event_associations_api import CalendarChannelEventAssociationsApi


class TestCalendarChannelEventAssociationsApi(unittest.TestCase):
    """CalendarChannelEventAssociationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CalendarChannelEventAssociationsApi()

    def tearDown(self) -> None:
        pass

    def test_create_many_calendar_channel_event_associations(self) -> None:
        """Test case for create_many_calendar_channel_event_associations

        Create Many calendarChannelEventAssociations
        """
        pass

    def test_create_one_calendar_channel_event_association(self) -> None:
        """Test case for create_one_calendar_channel_event_association

        Create One calendarChannelEventAssociation
        """
        pass

    def test_delete_many_calendar_channel_event_associations(self) -> None:
        """Test case for delete_many_calendar_channel_event_associations

        Delete Many calendarChannelEventAssociations
        """
        pass

    def test_delete_one_calendar_channel_event_association(self) -> None:
        """Test case for delete_one_calendar_channel_event_association

        Delete One calendarChannelEventAssociation
        """
        pass

    def test_find_calendar_channel_event_association_duplicates(self) -> None:
        """Test case for find_calendar_channel_event_association_duplicates

        Find calendarChannelEventAssociation Duplicates
        """
        pass

    def test_find_many_calendar_channel_event_associations(self) -> None:
        """Test case for find_many_calendar_channel_event_associations

        Find Many calendarChannelEventAssociations
        """
        pass

    def test_find_one_calendar_channel_event_association(self) -> None:
        """Test case for find_one_calendar_channel_event_association

        Find One calendarChannelEventAssociation
        """
        pass

    def test_group_by_calendar_channel_event_associations(self) -> None:
        """Test case for group_by_calendar_channel_event_associations

        Group By calendarChannelEventAssociations
        """
        pass

    def test_merge_many_calendar_channel_event_associations(self) -> None:
        """Test case for merge_many_calendar_channel_event_associations

        Merge Many calendarChannelEventAssociations
        """
        pass

    def test_restore_many_calendar_channel_event_associations(self) -> None:
        """Test case for restore_many_calendar_channel_event_associations

        Restore Many calendarChannelEventAssociations
        """
        pass

    def test_restore_one_calendar_channel_event_association(self) -> None:
        """Test case for restore_one_calendar_channel_event_association

        Restore One calendarChannelEventAssociation
        """
        pass

    def test_update_many_calendar_channel_event_associations(self) -> None:
        """Test case for update_many_calendar_channel_event_associations

        Update Many calendarChannelEventAssociations
        """
        pass

    def test_update_one_calendar_channel_event_association(self) -> None:
        """Test case for update_one_calendar_channel_event_association

        Update One calendarChannelEventAssociation
        """
        pass


if __name__ == '__main__':
    unittest.main()
