# coding: utf-8

"""
    Twenty Api

    Twenty is a customer relationship management (CRM) platform designed to help businesses manage their customer interactions and relationships effectively. The Twenty API provides programmatic access to the features and functionalities of the Twenty CRM platform, allowing developers to integrate and interact with the CRM data and operations.

    The version of the OpenAPI document: v0.1
    Contact: felix@twenty.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from twentycrm_client.api.calendar_channel_api import CalendarChannelApi


class TestCalendarChannelApi(unittest.TestCase):
    """CalendarChannelApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CalendarChannelApi()

    def tearDown(self) -> None:
        pass

    def test_calendar_channel_created_post(self) -> None:
        """Test case for calendar_channel_created_post

        """
        pass

    def test_calendar_channel_deleted_post(self) -> None:
        """Test case for calendar_channel_deleted_post

        """
        pass

    def test_calendar_channel_updated_post(self) -> None:
        """Test case for calendar_channel_updated_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
