# coding: utf-8

"""
    Twenty Api

    Twenty is a customer relationship management (CRM) platform designed to help businesses manage their customer interactions and relationships effectively. The Twenty API provides programmatic access to the features and functionalities of the Twenty CRM platform, allowing developers to integrate and interact with the CRM data and operations.

    The version of the OpenAPI document: v0.1
    Contact: felix@twenty.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from twentycrm_client.models.find_calendar_channel_duplicates_request import FindCalendarChannelDuplicatesRequest

class TestFindCalendarChannelDuplicatesRequest(unittest.TestCase):
    """FindCalendarChannelDuplicatesRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FindCalendarChannelDuplicatesRequest:
        """Test FindCalendarChannelDuplicatesRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FindCalendarChannelDuplicatesRequest`
        """
        model = FindCalendarChannelDuplicatesRequest()
        if include_optional:
            return FindCalendarChannelDuplicatesRequest(
                data = [
                    {visibility=METADATA, contactAutoCreationPolicy=AS_PARTICIPANT_AND_ORGANIZER, syncStatus=ONGOING, syncStage=CALENDAR_EVENT_LIST_FETCH_PENDING}
                    ],
                ids = [
                    ''
                    ]
            )
        else:
            return FindCalendarChannelDuplicatesRequest(
        )
        """

    def testFindCalendarChannelDuplicatesRequest(self):
        """Test FindCalendarChannelDuplicatesRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
