# coding: utf-8

"""
    Twenty Api

    Twenty is a customer relationship management (CRM) platform designed to help businesses manage their customer interactions and relationships effectively. The Twenty API provides programmatic access to the features and functionalities of the Twenty CRM platform, allowing developers to integrate and interact with the CRM data and operations.

    The version of the OpenAPI document: v0.1
    Contact: felix@twenty.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from twentycrm_client.models.delete_one_opportunity200_response_data import DeleteOneOpportunity200ResponseData

class TestDeleteOneOpportunity200ResponseData(unittest.TestCase):
    """DeleteOneOpportunity200ResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeleteOneOpportunity200ResponseData:
        """Test DeleteOneOpportunity200ResponseData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeleteOneOpportunity200ResponseData`
        """
        model = DeleteOneOpportunity200ResponseData()
        if include_optional:
            return DeleteOneOpportunity200ResponseData(
                delete_opportunity = twentycrm_client.models.delete_many_attachments_200_response_data_delete_attachments_inner.deleteManyAttachments_200_response_data_deleteAttachments_inner(
                    id = '', )
            )
        else:
            return DeleteOneOpportunity200ResponseData(
        )
        """

    def testDeleteOneOpportunity200ResponseData(self):
        """Test DeleteOneOpportunity200ResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
