# coding: utf-8

"""
    Twenty Api

    Twenty is a customer relationship management (CRM) platform designed to help businesses manage their customer interactions and relationships effectively. The Twenty API provides programmatic access to the features and functionalities of the Twenty CRM platform, allowing developers to integrate and interact with the CRM data and operations.

    The version of the OpenAPI document: v0.1
    Contact: felix@twenty.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from twentycrm_client.models.delete_many_workspace_members200_response_data import DeleteManyWorkspaceMembers200ResponseData

class TestDeleteManyWorkspaceMembers200ResponseData(unittest.TestCase):
    """DeleteManyWorkspaceMembers200ResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeleteManyWorkspaceMembers200ResponseData:
        """Test DeleteManyWorkspaceMembers200ResponseData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeleteManyWorkspaceMembers200ResponseData`
        """
        model = DeleteManyWorkspaceMembers200ResponseData()
        if include_optional:
            return DeleteManyWorkspaceMembers200ResponseData(
                delete_workspace_members = [
                    twentycrm_client.models.delete_many_attachments_200_response_data_delete_attachments_inner.deleteManyAttachments_200_response_data_deleteAttachments_inner(
                        id = '', )
                    ]
            )
        else:
            return DeleteManyWorkspaceMembers200ResponseData(
        )
        """

    def testDeleteManyWorkspaceMembers200ResponseData(self):
        """Test DeleteManyWorkspaceMembers200ResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
