# coding: utf-8

"""
    Twenty Api

    Twenty is a customer relationship management (CRM) platform designed to help businesses manage their customer interactions and relationships effectively. The Twenty API provides programmatic access to the features and functionalities of the Twenty CRM platform, allowing developers to integrate and interact with the CRM data and operations.

    The version of the OpenAPI document: v0.1
    Contact: felix@twenty.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from twentycrm_client.models.find_workflow_version_duplicates_request import FindWorkflowVersionDuplicatesRequest

class TestFindWorkflowVersionDuplicatesRequest(unittest.TestCase):
    """FindWorkflowVersionDuplicatesRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FindWorkflowVersionDuplicatesRequest:
        """Test FindWorkflowVersionDuplicatesRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FindWorkflowVersionDuplicatesRequest`
        """
        model = FindWorkflowVersionDuplicatesRequest()
        if include_optional:
            return FindWorkflowVersionDuplicatesRequest(
                data = [
                    {name=Workflow Version name, status=DRAFT}
                    ],
                ids = [
                    ''
                    ]
            )
        else:
            return FindWorkflowVersionDuplicatesRequest(
        )
        """

    def testFindWorkflowVersionDuplicatesRequest(self):
        """Test FindWorkflowVersionDuplicatesRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
