# coding: utf-8

"""
    Twenty Api

    Twenty is a customer relationship management (CRM) platform designed to help businesses manage their customer interactions and relationships effectively. The Twenty API provides programmatic access to the features and functionalities of the Twenty CRM platform, allowing developers to integrate and interact with the CRM data and operations.

    The version of the OpenAPI document: v0.1
    Contact: felix@twenty.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from twentycrm_client.api.message_threads_api import MessageThreadsApi


class TestMessageThreadsApi(unittest.TestCase):
    """MessageThreadsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MessageThreadsApi()

    def tearDown(self) -> None:
        pass

    def test_create_many_message_threads(self) -> None:
        """Test case for create_many_message_threads

        Create Many messageThreads
        """
        pass

    def test_create_one_message_thread(self) -> None:
        """Test case for create_one_message_thread

        Create One messageThread
        """
        pass

    def test_delete_many_message_threads(self) -> None:
        """Test case for delete_many_message_threads

        Delete Many messageThreads
        """
        pass

    def test_delete_one_message_thread(self) -> None:
        """Test case for delete_one_message_thread

        Delete One messageThread
        """
        pass

    def test_find_many_message_threads(self) -> None:
        """Test case for find_many_message_threads

        Find Many messageThreads
        """
        pass

    def test_find_message_thread_duplicates(self) -> None:
        """Test case for find_message_thread_duplicates

        Find messageThread Duplicates
        """
        pass

    def test_find_one_message_thread(self) -> None:
        """Test case for find_one_message_thread

        Find One messageThread
        """
        pass

    def test_group_by_message_threads(self) -> None:
        """Test case for group_by_message_threads

        Group By messageThreads
        """
        pass

    def test_merge_many_message_threads(self) -> None:
        """Test case for merge_many_message_threads

        Merge Many messageThreads
        """
        pass

    def test_restore_many_message_threads(self) -> None:
        """Test case for restore_many_message_threads

        Restore Many messageThreads
        """
        pass

    def test_restore_one_message_thread(self) -> None:
        """Test case for restore_one_message_thread

        Restore One messageThread
        """
        pass

    def test_update_many_message_threads(self) -> None:
        """Test case for update_many_message_threads

        Update Many messageThreads
        """
        pass

    def test_update_one_message_thread(self) -> None:
        """Test case for update_one_message_thread

        Update One messageThread
        """
        pass


if __name__ == '__main__':
    unittest.main()
