# coding: utf-8

"""
    Twenty Api

    Twenty is a customer relationship management (CRM) platform designed to help businesses manage their customer interactions and relationships effectively. The Twenty API provides programmatic access to the features and functionalities of the Twenty CRM platform, allowing developers to integrate and interact with the CRM data and operations.

    The version of the OpenAPI document: v0.1
    Contact: felix@twenty.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from twentycrm_client.api.people_api import PeopleApi


class TestPeopleApi(unittest.TestCase):
    """PeopleApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PeopleApi()

    def tearDown(self) -> None:
        pass

    def test_create_many_people(self) -> None:
        """Test case for create_many_people

        Create Many people
        """
        pass

    def test_create_one_person(self) -> None:
        """Test case for create_one_person

        Create One person
        """
        pass

    def test_delete_many_people(self) -> None:
        """Test case for delete_many_people

        Delete Many people
        """
        pass

    def test_delete_one_person(self) -> None:
        """Test case for delete_one_person

        Delete One person
        """
        pass

    def test_find_many_people(self) -> None:
        """Test case for find_many_people

        Find Many people
        """
        pass

    def test_find_one_person(self) -> None:
        """Test case for find_one_person

        Find One person
        """
        pass

    def test_find_person_duplicates(self) -> None:
        """Test case for find_person_duplicates

        Find person Duplicates
        """
        pass

    def test_group_by_people(self) -> None:
        """Test case for group_by_people

        Group By people
        """
        pass

    def test_merge_many_people(self) -> None:
        """Test case for merge_many_people

        Merge Many people
        """
        pass

    def test_restore_many_people(self) -> None:
        """Test case for restore_many_people

        Restore Many people
        """
        pass

    def test_restore_one_person(self) -> None:
        """Test case for restore_one_person

        Restore One person
        """
        pass

    def test_update_many_people(self) -> None:
        """Test case for update_many_people

        Update Many people
        """
        pass

    def test_update_one_person(self) -> None:
        """Test case for update_one_person

        Update One person
        """
        pass


if __name__ == '__main__':
    unittest.main()
