# coding: utf-8

"""
    Twenty Api

    Twenty is a customer relationship management (CRM) platform designed to help businesses manage their customer interactions and relationships effectively. The Twenty API provides programmatic access to the features and functionalities of the Twenty CRM platform, allowing developers to integrate and interact with the CRM data and operations.

    The version of the OpenAPI document: v0.1
    Contact: felix@twenty.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from twentycrm_client.models.timeline_activity import TimelineActivity

class TestTimelineActivity(unittest.TestCase):
    """TimelineActivity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TimelineActivity:
        """Test TimelineActivity
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TimelineActivity`
        """
        model = TimelineActivity()
        if include_optional:
            return TimelineActivity(
                happens_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                name = '',
                properties = None,
                linked_record_cached_name = '',
                linked_record_id = '',
                linked_object_metadata_id = '',
                target_company = '',
                target_dashboard = '',
                target_note = '',
                target_opportunity = '',
                target_person = '',
                target_task = '',
                workspace_member_id = '',
                target_workflow = '',
                target_workflow_version = '',
                target_workflow_run = ''
            )
        else:
            return TimelineActivity(
        )
        """

    def testTimelineActivity(self):
        """Test TimelineActivity"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
