# coding: utf-8

"""
    Twenty Api

    Twenty is a customer relationship management (CRM) platform designed to help businesses manage their customer interactions and relationships effectively. The Twenty API provides programmatic access to the features and functionalities of the Twenty CRM platform, allowing developers to integrate and interact with the CRM data and operations.

    The version of the OpenAPI document: v0.1
    Contact: felix@twenty.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from twentycrm_client.api.calendar_event_participants_api import CalendarEventParticipantsApi


class TestCalendarEventParticipantsApi(unittest.TestCase):
    """CalendarEventParticipantsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CalendarEventParticipantsApi()

    def tearDown(self) -> None:
        pass

    def test_create_many_calendar_event_participants(self) -> None:
        """Test case for create_many_calendar_event_participants

        Create Many calendarEventParticipants
        """
        pass

    def test_create_one_calendar_event_participant(self) -> None:
        """Test case for create_one_calendar_event_participant

        Create One calendarEventParticipant
        """
        pass

    def test_delete_many_calendar_event_participants(self) -> None:
        """Test case for delete_many_calendar_event_participants

        Delete Many calendarEventParticipants
        """
        pass

    def test_delete_one_calendar_event_participant(self) -> None:
        """Test case for delete_one_calendar_event_participant

        Delete One calendarEventParticipant
        """
        pass

    def test_find_calendar_event_participant_duplicates(self) -> None:
        """Test case for find_calendar_event_participant_duplicates

        Find calendarEventParticipant Duplicates
        """
        pass

    def test_find_many_calendar_event_participants(self) -> None:
        """Test case for find_many_calendar_event_participants

        Find Many calendarEventParticipants
        """
        pass

    def test_find_one_calendar_event_participant(self) -> None:
        """Test case for find_one_calendar_event_participant

        Find One calendarEventParticipant
        """
        pass

    def test_group_by_calendar_event_participants(self) -> None:
        """Test case for group_by_calendar_event_participants

        Group By calendarEventParticipants
        """
        pass

    def test_merge_many_calendar_event_participants(self) -> None:
        """Test case for merge_many_calendar_event_participants

        Merge Many calendarEventParticipants
        """
        pass

    def test_restore_many_calendar_event_participants(self) -> None:
        """Test case for restore_many_calendar_event_participants

        Restore Many calendarEventParticipants
        """
        pass

    def test_restore_one_calendar_event_participant(self) -> None:
        """Test case for restore_one_calendar_event_participant

        Restore One calendarEventParticipant
        """
        pass

    def test_update_many_calendar_event_participants(self) -> None:
        """Test case for update_many_calendar_event_participants

        Update Many calendarEventParticipants
        """
        pass

    def test_update_one_calendar_event_participant(self) -> None:
        """Test case for update_one_calendar_event_participant

        Update One calendarEventParticipant
        """
        pass


if __name__ == '__main__':
    unittest.main()
