# coding: utf-8

"""
    Twenty Api

    Twenty is a customer relationship management (CRM) platform designed to help businesses manage their customer interactions and relationships effectively. The Twenty API provides programmatic access to the features and functionalities of the Twenty CRM platform, allowing developers to integrate and interact with the CRM data and operations.

    The version of the OpenAPI document: v0.1
    Contact: felix@twenty.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from twentycrm_client.api.favorite_folders_api import FavoriteFoldersApi


class TestFavoriteFoldersApi(unittest.TestCase):
    """FavoriteFoldersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FavoriteFoldersApi()

    def tearDown(self) -> None:
        pass

    def test_create_many_favorite_folders(self) -> None:
        """Test case for create_many_favorite_folders

        Create Many favoriteFolders
        """
        pass

    def test_create_one_favorite_folder(self) -> None:
        """Test case for create_one_favorite_folder

        Create One favoriteFolder
        """
        pass

    def test_delete_many_favorite_folders(self) -> None:
        """Test case for delete_many_favorite_folders

        Delete Many favoriteFolders
        """
        pass

    def test_delete_one_favorite_folder(self) -> None:
        """Test case for delete_one_favorite_folder

        Delete One favoriteFolder
        """
        pass

    def test_find_favorite_folder_duplicates(self) -> None:
        """Test case for find_favorite_folder_duplicates

        Find favoriteFolder Duplicates
        """
        pass

    def test_find_many_favorite_folders(self) -> None:
        """Test case for find_many_favorite_folders

        Find Many favoriteFolders
        """
        pass

    def test_find_one_favorite_folder(self) -> None:
        """Test case for find_one_favorite_folder

        Find One favoriteFolder
        """
        pass

    def test_group_by_favorite_folders(self) -> None:
        """Test case for group_by_favorite_folders

        Group By favoriteFolders
        """
        pass

    def test_merge_many_favorite_folders(self) -> None:
        """Test case for merge_many_favorite_folders

        Merge Many favoriteFolders
        """
        pass

    def test_restore_many_favorite_folders(self) -> None:
        """Test case for restore_many_favorite_folders

        Restore Many favoriteFolders
        """
        pass

    def test_restore_one_favorite_folder(self) -> None:
        """Test case for restore_one_favorite_folder

        Restore One favoriteFolder
        """
        pass

    def test_update_many_favorite_folders(self) -> None:
        """Test case for update_many_favorite_folders

        Update Many favoriteFolders
        """
        pass

    def test_update_one_favorite_folder(self) -> None:
        """Test case for update_one_favorite_folder

        Update One favoriteFolder
        """
        pass


if __name__ == '__main__':
    unittest.main()
