# coding: utf-8

"""
    Twenty Api

    Twenty is a customer relationship management (CRM) platform designed to help businesses manage their customer interactions and relationships effectively. The Twenty API provides programmatic access to the features and functionalities of the Twenty CRM platform, allowing developers to integrate and interact with the CRM data and operations.

    The version of the OpenAPI document: v0.1
    Contact: felix@twenty.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from twentycrm_client.api.message_channel_message_associations_api import MessageChannelMessageAssociationsApi


class TestMessageChannelMessageAssociationsApi(unittest.TestCase):
    """MessageChannelMessageAssociationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MessageChannelMessageAssociationsApi()

    def tearDown(self) -> None:
        pass

    def test_create_many_message_channel_message_associations(self) -> None:
        """Test case for create_many_message_channel_message_associations

        Create Many messageChannelMessageAssociations
        """
        pass

    def test_create_one_message_channel_message_association(self) -> None:
        """Test case for create_one_message_channel_message_association

        Create One messageChannelMessageAssociation
        """
        pass

    def test_delete_many_message_channel_message_associations(self) -> None:
        """Test case for delete_many_message_channel_message_associations

        Delete Many messageChannelMessageAssociations
        """
        pass

    def test_delete_one_message_channel_message_association(self) -> None:
        """Test case for delete_one_message_channel_message_association

        Delete One messageChannelMessageAssociation
        """
        pass

    def test_find_many_message_channel_message_associations(self) -> None:
        """Test case for find_many_message_channel_message_associations

        Find Many messageChannelMessageAssociations
        """
        pass

    def test_find_message_channel_message_association_duplicates(self) -> None:
        """Test case for find_message_channel_message_association_duplicates

        Find messageChannelMessageAssociation Duplicates
        """
        pass

    def test_find_one_message_channel_message_association(self) -> None:
        """Test case for find_one_message_channel_message_association

        Find One messageChannelMessageAssociation
        """
        pass

    def test_group_by_message_channel_message_associations(self) -> None:
        """Test case for group_by_message_channel_message_associations

        Group By messageChannelMessageAssociations
        """
        pass

    def test_merge_many_message_channel_message_associations(self) -> None:
        """Test case for merge_many_message_channel_message_associations

        Merge Many messageChannelMessageAssociations
        """
        pass

    def test_restore_many_message_channel_message_associations(self) -> None:
        """Test case for restore_many_message_channel_message_associations

        Restore Many messageChannelMessageAssociations
        """
        pass

    def test_restore_one_message_channel_message_association(self) -> None:
        """Test case for restore_one_message_channel_message_association

        Restore One messageChannelMessageAssociation
        """
        pass

    def test_update_many_message_channel_message_associations(self) -> None:
        """Test case for update_many_message_channel_message_associations

        Update Many messageChannelMessageAssociations
        """
        pass

    def test_update_one_message_channel_message_association(self) -> None:
        """Test case for update_one_message_channel_message_association

        Update One messageChannelMessageAssociation
        """
        pass


if __name__ == '__main__':
    unittest.main()
