# coding: utf-8

"""
    Twenty Api

    Twenty is a customer relationship management (CRM) platform designed to help businesses manage their customer interactions and relationships effectively. The Twenty API provides programmatic access to the features and functionalities of the Twenty CRM platform, allowing developers to integrate and interact with the CRM data and operations.

    The version of the OpenAPI document: v0.1
    Contact: felix@twenty.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from twentycrm_client.models.connected_account_for_update import ConnectedAccountForUpdate

class TestConnectedAccountForUpdate(unittest.TestCase):
    """ConnectedAccountForUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConnectedAccountForUpdate:
        """Test ConnectedAccountForUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConnectedAccountForUpdate`
        """
        model = ConnectedAccountForUpdate()
        if include_optional:
            return ConnectedAccountForUpdate(
                handle = '',
                provider = '',
                access_token = '',
                refresh_token = '',
                last_sync_history_id = '',
                auth_failed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                last_credentials_refreshed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                handle_aliases = '',
                scopes = [
                    ''
                    ],
                connection_parameters = None,
                account_owner_id = ''
            )
        else:
            return ConnectedAccountForUpdate(
        )
        """

    def testConnectedAccountForUpdate(self):
        """Test ConnectedAccountForUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
