# coding: utf-8

"""
    Twenty Api

    Twenty is a customer relationship management (CRM) platform designed to help businesses manage their customer interactions and relationships effectively. The Twenty API provides programmatic access to the features and functionalities of the Twenty CRM platform, allowing developers to integrate and interact with the CRM data and operations.

    The version of the OpenAPI document: v0.1
    Contact: felix@twenty.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from twentycrm_client.api.message_thread_api import MessageThreadApi


class TestMessageThreadApi(unittest.TestCase):
    """MessageThreadApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MessageThreadApi()

    def tearDown(self) -> None:
        pass

    def test_message_thread_created_post(self) -> None:
        """Test case for message_thread_created_post

        """
        pass

    def test_message_thread_deleted_post(self) -> None:
        """Test case for message_thread_deleted_post

        """
        pass

    def test_message_thread_updated_post(self) -> None:
        """Test case for message_thread_updated_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
