# coding: utf-8

"""
    Twenty Api

    Twenty is a customer relationship management (CRM) platform designed to help businesses manage their customer interactions and relationships effectively. The Twenty API provides programmatic access to the features and functionalities of the Twenty CRM platform, allowing developers to integrate and interact with the CRM data and operations.

    The version of the OpenAPI document: v0.1
    Contact: felix@twenty.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from twentycrm_client.models.message_channel_message_association import MessageChannelMessageAssociation

class TestMessageChannelMessageAssociation(unittest.TestCase):
    """MessageChannelMessageAssociation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MessageChannelMessageAssociation:
        """Test MessageChannelMessageAssociation
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MessageChannelMessageAssociation`
        """
        model = MessageChannelMessageAssociation()
        if include_optional:
            return MessageChannelMessageAssociation(
                message_external_id = '',
                message_thread_external_id = '',
                direction = 'INCOMING',
                message_id = '',
                message_channel_id = '',
                message_thread_id = ''
            )
        else:
            return MessageChannelMessageAssociation(
        )
        """

    def testMessageChannelMessageAssociation(self):
        """Test MessageChannelMessageAssociation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
