# coding: utf-8

"""
    Twenty Api

    Twenty is a customer relationship management (CRM) platform designed to help businesses manage their customer interactions and relationships effectively. The Twenty API provides programmatic access to the features and functionalities of the Twenty CRM platform, allowing developers to integrate and interact with the CRM data and operations.

    The version of the OpenAPI document: v0.1
    Contact: felix@twenty.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from twentycrm_client.api.connected_accounts_api import ConnectedAccountsApi


class TestConnectedAccountsApi(unittest.TestCase):
    """ConnectedAccountsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ConnectedAccountsApi()

    def tearDown(self) -> None:
        pass

    def test_create_many_connected_accounts(self) -> None:
        """Test case for create_many_connected_accounts

        Create Many connectedAccounts
        """
        pass

    def test_create_one_connected_account(self) -> None:
        """Test case for create_one_connected_account

        Create One connectedAccount
        """
        pass

    def test_delete_many_connected_accounts(self) -> None:
        """Test case for delete_many_connected_accounts

        Delete Many connectedAccounts
        """
        pass

    def test_delete_one_connected_account(self) -> None:
        """Test case for delete_one_connected_account

        Delete One connectedAccount
        """
        pass

    def test_find_connected_account_duplicates(self) -> None:
        """Test case for find_connected_account_duplicates

        Find connectedAccount Duplicates
        """
        pass

    def test_find_many_connected_accounts(self) -> None:
        """Test case for find_many_connected_accounts

        Find Many connectedAccounts
        """
        pass

    def test_find_one_connected_account(self) -> None:
        """Test case for find_one_connected_account

        Find One connectedAccount
        """
        pass

    def test_group_by_connected_accounts(self) -> None:
        """Test case for group_by_connected_accounts

        Group By connectedAccounts
        """
        pass

    def test_merge_many_connected_accounts(self) -> None:
        """Test case for merge_many_connected_accounts

        Merge Many connectedAccounts
        """
        pass

    def test_restore_many_connected_accounts(self) -> None:
        """Test case for restore_many_connected_accounts

        Restore Many connectedAccounts
        """
        pass

    def test_restore_one_connected_account(self) -> None:
        """Test case for restore_one_connected_account

        Restore One connectedAccount
        """
        pass

    def test_update_many_connected_accounts(self) -> None:
        """Test case for update_many_connected_accounts

        Update Many connectedAccounts
        """
        pass

    def test_update_one_connected_account(self) -> None:
        """Test case for update_one_connected_account

        Update One connectedAccount
        """
        pass


if __name__ == '__main__':
    unittest.main()
