# coding: utf-8

"""
    Twenty Api

    Twenty is a customer relationship management (CRM) platform designed to help businesses manage their customer interactions and relationships effectively. The Twenty API provides programmatic access to the features and functionalities of the Twenty CRM platform, allowing developers to integrate and interact with the CRM data and operations.

    The version of the OpenAPI document: v0.1
    Contact: felix@twenty.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from twentycrm_client.models.attachment_updated_post_request import AttachmentUpdatedPostRequest

class TestAttachmentUpdatedPostRequest(unittest.TestCase):
    """AttachmentUpdatedPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AttachmentUpdatedPostRequest:
        """Test AttachmentUpdatedPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AttachmentUpdatedPostRequest`
        """
        model = AttachmentUpdatedPostRequest()
        if include_optional:
            return AttachmentUpdatedPostRequest(
                target_url = 'https://example.com/incomingWebhook',
                event_name = 'attachment.updated',
                object_metadata = twentycrm_client.models.attachment_created_post_request_object_metadata.Attachment_Created_post_request_objectMetadata(
                    id = '370985db-22d8-4463-8e5f-2271d30913bd', 
                    name_singular = 'attachment', ),
                workspace_id = '872cfcf1-c79f-42bc-877d-5829f06eb3f9',
                user_id = '170ba418-85a2-4f91-8565-9cd714c6703a',
                workspace_member_id = '9062a1e3-e066-49ba-8c4a-d869b6a0ca12',
                webhook_id = '90056586-1228-4e03-a507-70140aa85c05',
                event_date = '2024-02-14T11:27:01.779Z',
                record = twentycrm_client.models.attachment_for_response.AttachmentForResponse(
                    id = '', 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    deleted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    name = '', 
                    file = [
                        twentycrm_client.models.attachment_for_response_file_inner.AttachmentForResponse_file_inner(
                            file_id = '', 
                            label = '', 
                            extension = '', 
                            url = '', )
                        ], 
                    full_path = '', 
                    file_category = 'ARCHIVE', 
                    created_by = twentycrm_client.models.attachment_for_response_created_by.AttachmentForResponse_createdBy(
                        source = 'EMAIL', 
                        workspace_member_id = '', 
                        name = '', ), 
                    updated_by = twentycrm_client.models.attachment_for_response_updated_by.AttachmentForResponse_updatedBy(
                        source = 'EMAIL', 
                        workspace_member_id = '', 
                        name = '', ), 
                    target_note = '', 
                    target_task = '', 
                    target_person = '', 
                    target_company = '', 
                    target_opportunity = '', 
                    target_dashboard = '', 
                    target_workflow = '', ),
                updated_fields = [
                    ''
                    ]
            )
        else:
            return AttachmentUpdatedPostRequest(
        )
        """

    def testAttachmentUpdatedPostRequest(self):
        """Test AttachmentUpdatedPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
