# coding: utf-8

"""
    Twenty Api

    Twenty is a customer relationship management (CRM) platform designed to help businesses manage their customer interactions and relationships effectively. The Twenty API provides programmatic access to the features and functionalities of the Twenty CRM platform, allowing developers to integrate and interact with the CRM data and operations.

    The version of the OpenAPI document: v0.1
    Contact: felix@twenty.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from twentycrm_client.models.get_open_api_schema200_response import GetOpenApiSchema200Response

class TestGetOpenApiSchema200Response(unittest.TestCase):
    """GetOpenApiSchema200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetOpenApiSchema200Response:
        """Test GetOpenApiSchema200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetOpenApiSchema200Response`
        """
        model = GetOpenApiSchema200Response()
        if include_optional:
            return GetOpenApiSchema200Response(
                openapi = '',
                info = twentycrm_client.models.get_open_api_schema_200_response_info.GetOpenApiSchema_200_response_info(
                    title = '', 
                    description = '', 
                    terms_of_service = '', 
                    contact = twentycrm_client.models.get_open_api_schema_200_response_info_contact.GetOpenApiSchema_200_response_info_contact(
                        email = '', ), 
                    license = twentycrm_client.models.get_open_api_schema_200_response_info_license.GetOpenApiSchema_200_response_info_license(
                        name = '', 
                        url = '', ), ),
                servers = [
                    twentycrm_client.models.get_open_api_schema_200_response_servers_inner.GetOpenApiSchema_200_response_servers_inner(
                        url = '', 
                        description = '', )
                    ],
                components = twentycrm_client.models.get_open_api_schema_200_response_components.GetOpenApiSchema_200_response_components(
                    schemas = twentycrm_client.models.schemas.schemas(), 
                    parameters = twentycrm_client.models.parameters.parameters(), 
                    responses = twentycrm_client.models.parameters.parameters(), ),
                paths = twentycrm_client.models.parameters.parameters(),
                tags = twentycrm_client.models.parameters.parameters()
            )
        else:
            return GetOpenApiSchema200Response(
        )
        """

    def testGetOpenApiSchema200Response(self):
        """Test GetOpenApiSchema200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
