# coding: utf-8

"""
    Twenty Api

    Twenty is a customer relationship management (CRM) platform designed to help businesses manage their customer interactions and relationships effectively. The Twenty API provides programmatic access to the features and functionalities of the Twenty CRM platform, allowing developers to integrate and interact with the CRM data and operations.

    The version of the OpenAPI document: v0.1
    Contact: felix@twenty.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from twentycrm_client.models.message_folder_for_update import MessageFolderForUpdate

class TestMessageFolderForUpdate(unittest.TestCase):
    """MessageFolderForUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MessageFolderForUpdate:
        """Test MessageFolderForUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MessageFolderForUpdate`
        """
        model = MessageFolderForUpdate()
        if include_optional:
            return MessageFolderForUpdate(
                name = '',
                sync_cursor = '',
                is_sent_folder = True,
                is_synced = True,
                parent_folder_id = '',
                external_id = '',
                pending_sync_action = 'FOLDER_DELETION',
                message_channel_id = ''
            )
        else:
            return MessageFolderForUpdate(
        )
        """

    def testMessageFolderForUpdate(self):
        """Test MessageFolderForUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
