# coding: utf-8

"""
    Twenty Api

    Twenty is a customer relationship management (CRM) platform designed to help businesses manage their customer interactions and relationships effectively. The Twenty API provides programmatic access to the features and functionalities of the Twenty CRM platform, allowing developers to integrate and interact with the CRM data and operations.

    The version of the OpenAPI document: v0.1
    Contact: felix@twenty.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from twentycrm_client.models.calendar_event import CalendarEvent

class TestCalendarEvent(unittest.TestCase):
    """CalendarEvent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CalendarEvent:
        """Test CalendarEvent
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CalendarEvent`
        """
        model = CalendarEvent()
        if include_optional:
            return CalendarEvent(
                title = '',
                is_canceled = True,
                is_full_day = True,
                starts_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                ends_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                external_created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                external_updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                description = '',
                location = '',
                i_cal_uid = '',
                conference_solution = '',
                conference_link = twentycrm_client.models.calendar_event_conference_link.CalendarEvent_conferenceLink(
                    primary_link_label = '', 
                    primary_link_url = '', 
                    secondary_links = [
                        twentycrm_client.models.calendar_event_conference_link_secondary_links_inner.CalendarEvent_conferenceLink_secondaryLinks_inner(
                            url = '', 
                            label = '', )
                        ], )
            )
        else:
            return CalendarEvent(
        )
        """

    def testCalendarEvent(self):
        """Test CalendarEvent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
