# coding: utf-8

"""
    Twenty Api

    Twenty is a customer relationship management (CRM) platform designed to help businesses manage their customer interactions and relationships effectively. The Twenty API provides programmatic access to the features and functionalities of the Twenty CRM platform, allowing developers to integrate and interact with the CRM data and operations.

    The version of the OpenAPI document: v0.1
    Contact: felix@twenty.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from twentycrm_client.api.workflow_runs_api import WorkflowRunsApi


class TestWorkflowRunsApi(unittest.TestCase):
    """WorkflowRunsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WorkflowRunsApi()

    def tearDown(self) -> None:
        pass

    def test_create_many_workflow_runs(self) -> None:
        """Test case for create_many_workflow_runs

        Create Many workflowRuns
        """
        pass

    def test_create_one_workflow_run(self) -> None:
        """Test case for create_one_workflow_run

        Create One workflowRun
        """
        pass

    def test_delete_many_workflow_runs(self) -> None:
        """Test case for delete_many_workflow_runs

        Delete Many workflowRuns
        """
        pass

    def test_delete_one_workflow_run(self) -> None:
        """Test case for delete_one_workflow_run

        Delete One workflowRun
        """
        pass

    def test_find_many_workflow_runs(self) -> None:
        """Test case for find_many_workflow_runs

        Find Many workflowRuns
        """
        pass

    def test_find_one_workflow_run(self) -> None:
        """Test case for find_one_workflow_run

        Find One workflowRun
        """
        pass

    def test_find_workflow_run_duplicates(self) -> None:
        """Test case for find_workflow_run_duplicates

        Find workflowRun Duplicates
        """
        pass

    def test_group_by_workflow_runs(self) -> None:
        """Test case for group_by_workflow_runs

        Group By workflowRuns
        """
        pass

    def test_merge_many_workflow_runs(self) -> None:
        """Test case for merge_many_workflow_runs

        Merge Many workflowRuns
        """
        pass

    def test_restore_many_workflow_runs(self) -> None:
        """Test case for restore_many_workflow_runs

        Restore Many workflowRuns
        """
        pass

    def test_restore_one_workflow_run(self) -> None:
        """Test case for restore_one_workflow_run

        Restore One workflowRun
        """
        pass

    def test_update_many_workflow_runs(self) -> None:
        """Test case for update_many_workflow_runs

        Update Many workflowRuns
        """
        pass

    def test_update_one_workflow_run(self) -> None:
        """Test case for update_one_workflow_run

        Update One workflowRun
        """
        pass


if __name__ == '__main__':
    unittest.main()
