# coding: utf-8

"""
    Twenty Api

    Twenty is a customer relationship management (CRM) platform designed to help businesses manage their customer interactions and relationships effectively. The Twenty API provides programmatic access to the features and functionalities of the Twenty CRM platform, allowing developers to integrate and interact with the CRM data and operations.

    The version of the OpenAPI document: v0.1
    Contact: felix@twenty.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from twentycrm_client.models.message_channel_for_update import MessageChannelForUpdate

class TestMessageChannelForUpdate(unittest.TestCase):
    """MessageChannelForUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MessageChannelForUpdate:
        """Test MessageChannelForUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MessageChannelForUpdate`
        """
        model = MessageChannelForUpdate()
        if include_optional:
            return MessageChannelForUpdate(
                visibility = 'METADATA',
                handle = '',
                type = 'EMAIL',
                is_contact_auto_creation_enabled = True,
                contact_auto_creation_policy = 'SENT_AND_RECEIVED',
                message_folder_import_policy = 'ALL_FOLDERS',
                exclude_non_professional_emails = True,
                exclude_group_emails = True,
                pending_group_emails_action = 'GROUP_EMAILS_DELETION',
                is_sync_enabled = True,
                sync_cursor = '',
                synced_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                sync_status = 'ONGOING',
                sync_stage = 'MESSAGE_LIST_FETCH_PENDING',
                sync_stage_started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                throttle_failure_count = 56,
                throttle_retry_after = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                connected_account_id = ''
            )
        else:
            return MessageChannelForUpdate(
        )
        """

    def testMessageChannelForUpdate(self):
        """Test MessageChannelForUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
