# coding: utf-8

"""
    Twenty Api

    Twenty is a customer relationship management (CRM) platform designed to help businesses manage their customer interactions and relationships effectively. The Twenty API provides programmatic access to the features and functionalities of the Twenty CRM platform, allowing developers to integrate and interact with the CRM data and operations.

    The version of the OpenAPI document: v0.1
    Contact: felix@twenty.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from twentycrm_client.models.favorite_folder_for_update import FavoriteFolderForUpdate

class TestFavoriteFolderForUpdate(unittest.TestCase):
    """FavoriteFolderForUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FavoriteFolderForUpdate:
        """Test FavoriteFolderForUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FavoriteFolderForUpdate`
        """
        model = FavoriteFolderForUpdate()
        if include_optional:
            return FavoriteFolderForUpdate(
                position = 56,
                name = ''
            )
        else:
            return FavoriteFolderForUpdate(
        )
        """

    def testFavoriteFolderForUpdate(self):
        """Test FavoriteFolderForUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
