# coding: utf-8

"""
    Twenty Api

    Twenty is a customer relationship management (CRM) platform designed to help businesses manage their customer interactions and relationships effectively. The Twenty API provides programmatic access to the features and functionalities of the Twenty CRM platform, allowing developers to integrate and interact with the CRM data and operations.

    The version of the OpenAPI document: v0.1
    Contact: felix@twenty.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from twentycrm_client.models.group_by_message_channel_message_associations200_response_data import GroupByMessageChannelMessageAssociations200ResponseData

class TestGroupByMessageChannelMessageAssociations200ResponseData(unittest.TestCase):
    """GroupByMessageChannelMessageAssociations200ResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GroupByMessageChannelMessageAssociations200ResponseData:
        """Test GroupByMessageChannelMessageAssociations200ResponseData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GroupByMessageChannelMessageAssociations200ResponseData`
        """
        model = GroupByMessageChannelMessageAssociations200ResponseData()
        if include_optional:
            return GroupByMessageChannelMessageAssociations200ResponseData(
                message_channel_message_associations_group_by = [
                    {
                        'key' : 1.337
                        }
                    ]
            )
        else:
            return GroupByMessageChannelMessageAssociations200ResponseData(
        )
        """

    def testGroupByMessageChannelMessageAssociations200ResponseData(self):
        """Test GroupByMessageChannelMessageAssociations200ResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
