# coding: utf-8

"""
    Twenty Api

    Twenty is a customer relationship management (CRM) platform designed to help businesses manage their customer interactions and relationships effectively. The Twenty API provides programmatic access to the features and functionalities of the Twenty CRM platform, allowing developers to integrate and interact with the CRM data and operations.

    The version of the OpenAPI document: v0.1
    Contact: felix@twenty.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from twentycrm_client.models.get_open_api_schema200_response_servers_inner import GetOpenApiSchema200ResponseServersInner

class TestGetOpenApiSchema200ResponseServersInner(unittest.TestCase):
    """GetOpenApiSchema200ResponseServersInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetOpenApiSchema200ResponseServersInner:
        """Test GetOpenApiSchema200ResponseServersInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetOpenApiSchema200ResponseServersInner`
        """
        model = GetOpenApiSchema200ResponseServersInner()
        if include_optional:
            return GetOpenApiSchema200ResponseServersInner(
                url = '',
                description = ''
            )
        else:
            return GetOpenApiSchema200ResponseServersInner(
        )
        """

    def testGetOpenApiSchema200ResponseServersInner(self):
        """Test GetOpenApiSchema200ResponseServersInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
