# coding: utf-8

"""
    Twenty Api

    Twenty is a customer relationship management (CRM) platform designed to help businesses manage their customer interactions and relationships effectively. The Twenty API provides programmatic access to the features and functionalities of the Twenty CRM platform, allowing developers to integrate and interact with the CRM data and operations.

    The version of the OpenAPI document: v0.1
    Contact: felix@twenty.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from twentycrm_client.api.message_folders_api import MessageFoldersApi


class TestMessageFoldersApi(unittest.TestCase):
    """MessageFoldersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MessageFoldersApi()

    def tearDown(self) -> None:
        pass

    def test_create_many_message_folders(self) -> None:
        """Test case for create_many_message_folders

        Create Many messageFolders
        """
        pass

    def test_create_one_message_folder(self) -> None:
        """Test case for create_one_message_folder

        Create One messageFolder
        """
        pass

    def test_delete_many_message_folders(self) -> None:
        """Test case for delete_many_message_folders

        Delete Many messageFolders
        """
        pass

    def test_delete_one_message_folder(self) -> None:
        """Test case for delete_one_message_folder

        Delete One messageFolder
        """
        pass

    def test_find_many_message_folders(self) -> None:
        """Test case for find_many_message_folders

        Find Many messageFolders
        """
        pass

    def test_find_message_folder_duplicates(self) -> None:
        """Test case for find_message_folder_duplicates

        Find messageFolder Duplicates
        """
        pass

    def test_find_one_message_folder(self) -> None:
        """Test case for find_one_message_folder

        Find One messageFolder
        """
        pass

    def test_group_by_message_folders(self) -> None:
        """Test case for group_by_message_folders

        Group By messageFolders
        """
        pass

    def test_merge_many_message_folders(self) -> None:
        """Test case for merge_many_message_folders

        Merge Many messageFolders
        """
        pass

    def test_restore_many_message_folders(self) -> None:
        """Test case for restore_many_message_folders

        Restore Many messageFolders
        """
        pass

    def test_restore_one_message_folder(self) -> None:
        """Test case for restore_one_message_folder

        Restore One messageFolder
        """
        pass

    def test_update_many_message_folders(self) -> None:
        """Test case for update_many_message_folders

        Update Many messageFolders
        """
        pass

    def test_update_one_message_folder(self) -> None:
        """Test case for update_one_message_folder

        Update One messageFolder
        """
        pass


if __name__ == '__main__':
    unittest.main()
