# coding: utf-8

"""
    Twenty Api

    Twenty is a customer relationship management (CRM) platform designed to help businesses manage their customer interactions and relationships effectively. The Twenty API provides programmatic access to the features and functionalities of the Twenty CRM platform, allowing developers to integrate and interact with the CRM data and operations.

    The version of the OpenAPI document: v0.1
    Contact: felix@twenty.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from twentycrm_client.models.delete_many_companies200_response import DeleteManyCompanies200Response

class TestDeleteManyCompanies200Response(unittest.TestCase):
    """DeleteManyCompanies200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeleteManyCompanies200Response:
        """Test DeleteManyCompanies200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeleteManyCompanies200Response`
        """
        model = DeleteManyCompanies200Response()
        if include_optional:
            return DeleteManyCompanies200Response(
                data = twentycrm_client.models.delete_many_companies_200_response_data.deleteManyCompanies_200_response_data(
                    delete_companies = [
                        twentycrm_client.models.delete_many_attachments_200_response_data_delete_attachments_inner.deleteManyAttachments_200_response_data_deleteAttachments_inner(
                            id = '', )
                        ], )
            )
        else:
            return DeleteManyCompanies200Response(
        )
        """

    def testDeleteManyCompanies200Response(self):
        """Test DeleteManyCompanies200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
