# coding: utf-8

"""
    Twenty Api

    Twenty is a customer relationship management (CRM) platform designed to help businesses manage their customer interactions and relationships effectively. The Twenty API provides programmatic access to the features and functionalities of the Twenty CRM platform, allowing developers to integrate and interact with the CRM data and operations.

    The version of the OpenAPI document: v0.1
    Contact: felix@twenty.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from twentycrm_client.models.find_many_attachments200_response import FindManyAttachments200Response

class TestFindManyAttachments200Response(unittest.TestCase):
    """FindManyAttachments200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FindManyAttachments200Response:
        """Test FindManyAttachments200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FindManyAttachments200Response`
        """
        model = FindManyAttachments200Response()
        if include_optional:
            return FindManyAttachments200Response(
                data = twentycrm_client.models.find_many_attachments_200_response_data.findManyAttachments_200_response_data(
                    attachments = [
                        twentycrm_client.models.attachment_for_response.AttachmentForResponse(
                            id = '', 
                            created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            deleted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            name = '', 
                            file = [
                                twentycrm_client.models.attachment_for_response_file_inner.AttachmentForResponse_file_inner(
                                    file_id = '', 
                                    label = '', 
                                    extension = '', 
                                    url = '', )
                                ], 
                            full_path = '', 
                            file_category = 'ARCHIVE', 
                            created_by = twentycrm_client.models.attachment_for_response_created_by.AttachmentForResponse_createdBy(
                                source = 'EMAIL', 
                                workspace_member_id = '', 
                                name = '', ), 
                            updated_by = twentycrm_client.models.attachment_for_response_updated_by.AttachmentForResponse_updatedBy(
                                source = 'EMAIL', 
                                workspace_member_id = '', 
                                name = '', ), 
                            target_note = '', 
                            target_task = '', 
                            target_person = '', 
                            target_company = '', 
                            target_opportunity = '', 
                            target_dashboard = '', 
                            target_workflow = '', )
                        ], ),
                page_info = twentycrm_client.models.find_many_attachments_200_response_page_info.findManyAttachments_200_response_pageInfo(
                    has_next_page = True, 
                    start_cursor = '', 
                    end_cursor = '', ),
                total_count = 56
            )
        else:
            return FindManyAttachments200Response(
        )
        """

    def testFindManyAttachments200Response(self):
        """Test FindManyAttachments200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
