# coding: utf-8

"""
    Twenty Api

    Twenty is a customer relationship management (CRM) platform designed to help businesses manage their customer interactions and relationships effectively. The Twenty API provides programmatic access to the features and functionalities of the Twenty CRM platform, allowing developers to integrate and interact with the CRM data and operations.

    The version of the OpenAPI document: v0.1
    Contact: felix@twenty.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from twentycrm_client.api.dashboards_api import DashboardsApi


class TestDashboardsApi(unittest.TestCase):
    """DashboardsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DashboardsApi()

    def tearDown(self) -> None:
        pass

    def test_create_many_dashboards(self) -> None:
        """Test case for create_many_dashboards

        Create Many dashboards
        """
        pass

    def test_create_one_dashboard(self) -> None:
        """Test case for create_one_dashboard

        Create One dashboard
        """
        pass

    def test_delete_many_dashboards(self) -> None:
        """Test case for delete_many_dashboards

        Delete Many dashboards
        """
        pass

    def test_delete_one_dashboard(self) -> None:
        """Test case for delete_one_dashboard

        Delete One dashboard
        """
        pass

    def test_duplicate_dashboard(self) -> None:
        """Test case for duplicate_dashboard

        Duplicate a dashboard
        """
        pass

    def test_find_dashboard_duplicates(self) -> None:
        """Test case for find_dashboard_duplicates

        Find dashboard Duplicates
        """
        pass

    def test_find_many_dashboards(self) -> None:
        """Test case for find_many_dashboards

        Find Many dashboards
        """
        pass

    def test_find_one_dashboard(self) -> None:
        """Test case for find_one_dashboard

        Find One dashboard
        """
        pass

    def test_group_by_dashboards(self) -> None:
        """Test case for group_by_dashboards

        Group By dashboards
        """
        pass

    def test_merge_many_dashboards(self) -> None:
        """Test case for merge_many_dashboards

        Merge Many dashboards
        """
        pass

    def test_restore_many_dashboards(self) -> None:
        """Test case for restore_many_dashboards

        Restore Many dashboards
        """
        pass

    def test_restore_one_dashboard(self) -> None:
        """Test case for restore_one_dashboard

        Restore One dashboard
        """
        pass

    def test_update_many_dashboards(self) -> None:
        """Test case for update_many_dashboards

        Update Many dashboards
        """
        pass

    def test_update_one_dashboard(self) -> None:
        """Test case for update_one_dashboard

        Update One dashboard
        """
        pass


if __name__ == '__main__':
    unittest.main()
