# coding: utf-8

"""
    Twenty Api

    Twenty is a customer relationship management (CRM) platform designed to help businesses manage their customer interactions and relationships effectively. The Twenty API provides programmatic access to the features and functionalities of the Twenty CRM platform, allowing developers to integrate and interact with the CRM data and operations.

    The version of the OpenAPI document: v0.1
    Contact: felix@twenty.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from twentycrm_client.api.tasks_api import TasksApi


class TestTasksApi(unittest.TestCase):
    """TasksApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TasksApi()

    def tearDown(self) -> None:
        pass

    def test_create_many_tasks(self) -> None:
        """Test case for create_many_tasks

        Create Many tasks
        """
        pass

    def test_create_one_task(self) -> None:
        """Test case for create_one_task

        Create One task
        """
        pass

    def test_delete_many_tasks(self) -> None:
        """Test case for delete_many_tasks

        Delete Many tasks
        """
        pass

    def test_delete_one_task(self) -> None:
        """Test case for delete_one_task

        Delete One task
        """
        pass

    def test_find_many_tasks(self) -> None:
        """Test case for find_many_tasks

        Find Many tasks
        """
        pass

    def test_find_one_task(self) -> None:
        """Test case for find_one_task

        Find One task
        """
        pass

    def test_find_task_duplicates(self) -> None:
        """Test case for find_task_duplicates

        Find task Duplicates
        """
        pass

    def test_group_by_tasks(self) -> None:
        """Test case for group_by_tasks

        Group By tasks
        """
        pass

    def test_merge_many_tasks(self) -> None:
        """Test case for merge_many_tasks

        Merge Many tasks
        """
        pass

    def test_restore_many_tasks(self) -> None:
        """Test case for restore_many_tasks

        Restore Many tasks
        """
        pass

    def test_restore_one_task(self) -> None:
        """Test case for restore_one_task

        Restore One task
        """
        pass

    def test_update_many_tasks(self) -> None:
        """Test case for update_many_tasks

        Update Many tasks
        """
        pass

    def test_update_one_task(self) -> None:
        """Test case for update_one_task

        Update One task
        """
        pass


if __name__ == '__main__':
    unittest.main()
