# coding: utf-8

"""
    Twenty Api

    Twenty is a customer relationship management (CRM) platform designed to help businesses manage their customer interactions and relationships effectively. The Twenty API provides programmatic access to the features and functionalities of the Twenty CRM platform, allowing developers to integrate and interact with the CRM data and operations.

    The version of the OpenAPI document: v0.1
    Contact: felix@twenty.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from twentycrm_client.api.workflow_versions_api import WorkflowVersionsApi


class TestWorkflowVersionsApi(unittest.TestCase):
    """WorkflowVersionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WorkflowVersionsApi()

    def tearDown(self) -> None:
        pass

    def test_create_many_workflow_versions(self) -> None:
        """Test case for create_many_workflow_versions

        Create Many workflowVersions
        """
        pass

    def test_create_one_workflow_version(self) -> None:
        """Test case for create_one_workflow_version

        Create One workflowVersion
        """
        pass

    def test_delete_many_workflow_versions(self) -> None:
        """Test case for delete_many_workflow_versions

        Delete Many workflowVersions
        """
        pass

    def test_delete_one_workflow_version(self) -> None:
        """Test case for delete_one_workflow_version

        Delete One workflowVersion
        """
        pass

    def test_find_many_workflow_versions(self) -> None:
        """Test case for find_many_workflow_versions

        Find Many workflowVersions
        """
        pass

    def test_find_one_workflow_version(self) -> None:
        """Test case for find_one_workflow_version

        Find One workflowVersion
        """
        pass

    def test_find_workflow_version_duplicates(self) -> None:
        """Test case for find_workflow_version_duplicates

        Find workflowVersion Duplicates
        """
        pass

    def test_group_by_workflow_versions(self) -> None:
        """Test case for group_by_workflow_versions

        Group By workflowVersions
        """
        pass

    def test_merge_many_workflow_versions(self) -> None:
        """Test case for merge_many_workflow_versions

        Merge Many workflowVersions
        """
        pass

    def test_restore_many_workflow_versions(self) -> None:
        """Test case for restore_many_workflow_versions

        Restore Many workflowVersions
        """
        pass

    def test_restore_one_workflow_version(self) -> None:
        """Test case for restore_one_workflow_version

        Restore One workflowVersion
        """
        pass

    def test_update_many_workflow_versions(self) -> None:
        """Test case for update_many_workflow_versions

        Update Many workflowVersions
        """
        pass

    def test_update_one_workflow_version(self) -> None:
        """Test case for update_one_workflow_version

        Update One workflowVersion
        """
        pass


if __name__ == '__main__':
    unittest.main()
