# coding: utf-8

"""
    Twenty Api

    Twenty is a customer relationship management (CRM) platform designed to help businesses manage their customer interactions and relationships effectively. The Twenty API provides programmatic access to the features and functionalities of the Twenty CRM platform, allowing developers to integrate and interact with the CRM data and operations.

    The version of the OpenAPI document: v0.1
    Contact: felix@twenty.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from twentycrm_client.models.group_by_workflow_runs200_response import GroupByWorkflowRuns200Response

class TestGroupByWorkflowRuns200Response(unittest.TestCase):
    """GroupByWorkflowRuns200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GroupByWorkflowRuns200Response:
        """Test GroupByWorkflowRuns200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GroupByWorkflowRuns200Response`
        """
        model = GroupByWorkflowRuns200Response()
        if include_optional:
            return GroupByWorkflowRuns200Response(
                data = twentycrm_client.models.group_by_workflow_runs_200_response_data.groupByWorkflowRuns_200_response_data(
                    workflow_runs_group_by = [
                        {
                            'key' : 1.337
                            }
                        ], )
            )
        else:
            return GroupByWorkflowRuns200Response(
        )
        """

    def testGroupByWorkflowRuns200Response(self):
        """Test GroupByWorkflowRuns200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
