# coding: utf-8

"""
    Twenty Api

    Twenty is a customer relationship management (CRM) platform designed to help businesses manage their customer interactions and relationships effectively. The Twenty API provides programmatic access to the features and functionalities of the Twenty CRM platform, allowing developers to integrate and interact with the CRM data and operations.

    The version of the OpenAPI document: v0.1
    Contact: felix@twenty.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from twentycrm_client.api.workflow_automated_triggers_api import WorkflowAutomatedTriggersApi


class TestWorkflowAutomatedTriggersApi(unittest.TestCase):
    """WorkflowAutomatedTriggersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WorkflowAutomatedTriggersApi()

    def tearDown(self) -> None:
        pass

    def test_create_many_workflow_automated_triggers(self) -> None:
        """Test case for create_many_workflow_automated_triggers

        Create Many workflowAutomatedTriggers
        """
        pass

    def test_create_one_workflow_automated_trigger(self) -> None:
        """Test case for create_one_workflow_automated_trigger

        Create One workflowAutomatedTrigger
        """
        pass

    def test_delete_many_workflow_automated_triggers(self) -> None:
        """Test case for delete_many_workflow_automated_triggers

        Delete Many workflowAutomatedTriggers
        """
        pass

    def test_delete_one_workflow_automated_trigger(self) -> None:
        """Test case for delete_one_workflow_automated_trigger

        Delete One workflowAutomatedTrigger
        """
        pass

    def test_find_many_workflow_automated_triggers(self) -> None:
        """Test case for find_many_workflow_automated_triggers

        Find Many workflowAutomatedTriggers
        """
        pass

    def test_find_one_workflow_automated_trigger(self) -> None:
        """Test case for find_one_workflow_automated_trigger

        Find One workflowAutomatedTrigger
        """
        pass

    def test_find_workflow_automated_trigger_duplicates(self) -> None:
        """Test case for find_workflow_automated_trigger_duplicates

        Find workflowAutomatedTrigger Duplicates
        """
        pass

    def test_group_by_workflow_automated_triggers(self) -> None:
        """Test case for group_by_workflow_automated_triggers

        Group By workflowAutomatedTriggers
        """
        pass

    def test_merge_many_workflow_automated_triggers(self) -> None:
        """Test case for merge_many_workflow_automated_triggers

        Merge Many workflowAutomatedTriggers
        """
        pass

    def test_restore_many_workflow_automated_triggers(self) -> None:
        """Test case for restore_many_workflow_automated_triggers

        Restore Many workflowAutomatedTriggers
        """
        pass

    def test_restore_one_workflow_automated_trigger(self) -> None:
        """Test case for restore_one_workflow_automated_trigger

        Restore One workflowAutomatedTrigger
        """
        pass

    def test_update_many_workflow_automated_triggers(self) -> None:
        """Test case for update_many_workflow_automated_triggers

        Update Many workflowAutomatedTriggers
        """
        pass

    def test_update_one_workflow_automated_trigger(self) -> None:
        """Test case for update_one_workflow_automated_trigger

        Update One workflowAutomatedTrigger
        """
        pass


if __name__ == '__main__':
    unittest.main()
