# coding: utf-8

"""
    Twenty Api

    Twenty is a customer relationship management (CRM) platform designed to help businesses manage their customer interactions and relationships effectively. The Twenty API provides programmatic access to the features and functionalities of the Twenty CRM platform, allowing developers to integrate and interact with the CRM data and operations.

    The version of the OpenAPI document: v0.1
    Contact: felix@twenty.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from twentycrm_client.api.companies_api import CompaniesApi


class TestCompaniesApi(unittest.TestCase):
    """CompaniesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CompaniesApi()

    def tearDown(self) -> None:
        pass

    def test_create_many_companies(self) -> None:
        """Test case for create_many_companies

        Create Many companies
        """
        pass

    def test_create_one_company(self) -> None:
        """Test case for create_one_company

        Create One company
        """
        pass

    def test_delete_many_companies(self) -> None:
        """Test case for delete_many_companies

        Delete Many companies
        """
        pass

    def test_delete_one_company(self) -> None:
        """Test case for delete_one_company

        Delete One company
        """
        pass

    def test_find_company_duplicates(self) -> None:
        """Test case for find_company_duplicates

        Find company Duplicates
        """
        pass

    def test_find_many_companies(self) -> None:
        """Test case for find_many_companies

        Find Many companies
        """
        pass

    def test_find_one_company(self) -> None:
        """Test case for find_one_company

        Find One company
        """
        pass

    def test_group_by_companies(self) -> None:
        """Test case for group_by_companies

        Group By companies
        """
        pass

    def test_merge_many_companies(self) -> None:
        """Test case for merge_many_companies

        Merge Many companies
        """
        pass

    def test_restore_many_companies(self) -> None:
        """Test case for restore_many_companies

        Restore Many companies
        """
        pass

    def test_restore_one_company(self) -> None:
        """Test case for restore_one_company

        Restore One company
        """
        pass

    def test_update_many_companies(self) -> None:
        """Test case for update_many_companies

        Update Many companies
        """
        pass

    def test_update_one_company(self) -> None:
        """Test case for update_one_company

        Update One company
        """
        pass


if __name__ == '__main__':
    unittest.main()
