# coding: utf-8

"""
    Twenty Api

    Twenty is a customer relationship management (CRM) platform designed to help businesses manage their customer interactions and relationships effectively. The Twenty API provides programmatic access to the features and functionalities of the Twenty CRM platform, allowing developers to integrate and interact with the CRM data and operations.

    The version of the OpenAPI document: v0.1
    Contact: felix@twenty.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from twentycrm_client.models.group_by_task_targets200_response import GroupByTaskTargets200Response

class TestGroupByTaskTargets200Response(unittest.TestCase):
    """GroupByTaskTargets200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GroupByTaskTargets200Response:
        """Test GroupByTaskTargets200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GroupByTaskTargets200Response`
        """
        model = GroupByTaskTargets200Response()
        if include_optional:
            return GroupByTaskTargets200Response(
                data = twentycrm_client.models.group_by_task_targets_200_response_data.groupByTaskTargets_200_response_data(
                    task_targets_group_by = [
                        {
                            'key' : 1.337
                            }
                        ], )
            )
        else:
            return GroupByTaskTargets200Response(
        )
        """

    def testGroupByTaskTargets200Response(self):
        """Test GroupByTaskTargets200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
