# coding: utf-8

"""
    Twenty Api

    Twenty is a customer relationship management (CRM) platform designed to help businesses manage their customer interactions and relationships effectively. The Twenty API provides programmatic access to the features and functionalities of the Twenty CRM platform, allowing developers to integrate and interact with the CRM data and operations.

    The version of the OpenAPI document: v0.1
    Contact: felix@twenty.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from twentycrm_client.models.delete_many_favorites200_response import DeleteManyFavorites200Response

class TestDeleteManyFavorites200Response(unittest.TestCase):
    """DeleteManyFavorites200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeleteManyFavorites200Response:
        """Test DeleteManyFavorites200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeleteManyFavorites200Response`
        """
        model = DeleteManyFavorites200Response()
        if include_optional:
            return DeleteManyFavorites200Response(
                data = twentycrm_client.models.delete_many_favorites_200_response_data.deleteManyFavorites_200_response_data(
                    delete_favorites = [
                        twentycrm_client.models.delete_many_attachments_200_response_data_delete_attachments_inner.deleteManyAttachments_200_response_data_deleteAttachments_inner(
                            id = '', )
                        ], )
            )
        else:
            return DeleteManyFavorites200Response(
        )
        """

    def testDeleteManyFavorites200Response(self):
        """Test DeleteManyFavorites200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
