# coding: utf-8

"""
    Twenty Api

    Twenty is a customer relationship management (CRM) platform designed to help businesses manage their customer interactions and relationships effectively. The Twenty API provides programmatic access to the features and functionalities of the Twenty CRM platform, allowing developers to integrate and interact with the CRM data and operations.

    The version of the OpenAPI document: v0.1
    Contact: felix@twenty.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from twentycrm_client.api.blocklists_api import BlocklistsApi


class TestBlocklistsApi(unittest.TestCase):
    """BlocklistsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BlocklistsApi()

    def tearDown(self) -> None:
        pass

    def test_create_many_blocklists(self) -> None:
        """Test case for create_many_blocklists

        Create Many blocklists
        """
        pass

    def test_create_one_blocklist(self) -> None:
        """Test case for create_one_blocklist

        Create One blocklist
        """
        pass

    def test_delete_many_blocklists(self) -> None:
        """Test case for delete_many_blocklists

        Delete Many blocklists
        """
        pass

    def test_delete_one_blocklist(self) -> None:
        """Test case for delete_one_blocklist

        Delete One blocklist
        """
        pass

    def test_find_blocklist_duplicates(self) -> None:
        """Test case for find_blocklist_duplicates

        Find blocklist Duplicates
        """
        pass

    def test_find_many_blocklists(self) -> None:
        """Test case for find_many_blocklists

        Find Many blocklists
        """
        pass

    def test_find_one_blocklist(self) -> None:
        """Test case for find_one_blocklist

        Find One blocklist
        """
        pass

    def test_group_by_blocklists(self) -> None:
        """Test case for group_by_blocklists

        Group By blocklists
        """
        pass

    def test_merge_many_blocklists(self) -> None:
        """Test case for merge_many_blocklists

        Merge Many blocklists
        """
        pass

    def test_restore_many_blocklists(self) -> None:
        """Test case for restore_many_blocklists

        Restore Many blocklists
        """
        pass

    def test_restore_one_blocklist(self) -> None:
        """Test case for restore_one_blocklist

        Restore One blocklist
        """
        pass

    def test_update_many_blocklists(self) -> None:
        """Test case for update_many_blocklists

        Update Many blocklists
        """
        pass

    def test_update_one_blocklist(self) -> None:
        """Test case for update_one_blocklist

        Update One blocklist
        """
        pass


if __name__ == '__main__':
    unittest.main()
