# coding: utf-8

"""
    Twenty Api

    Twenty is a customer relationship management (CRM) platform designed to help businesses manage their customer interactions and relationships effectively. The Twenty API provides programmatic access to the features and functionalities of the Twenty CRM platform, allowing developers to integrate and interact with the CRM data and operations.

    The version of the OpenAPI document: v0.1
    Contact: felix@twenty.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from twentycrm_client.api.calendar_event_api import CalendarEventApi


class TestCalendarEventApi(unittest.TestCase):
    """CalendarEventApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CalendarEventApi()

    def tearDown(self) -> None:
        pass

    def test_calendar_event_created_post(self) -> None:
        """Test case for calendar_event_created_post

        """
        pass

    def test_calendar_event_deleted_post(self) -> None:
        """Test case for calendar_event_deleted_post

        """
        pass

    def test_calendar_event_updated_post(self) -> None:
        """Test case for calendar_event_updated_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
