# coding: utf-8

"""
    Twenty Api

    Twenty is a customer relationship management (CRM) platform designed to help businesses manage their customer interactions and relationships effectively. The Twenty API provides programmatic access to the features and functionalities of the Twenty CRM platform, allowing developers to integrate and interact with the CRM data and operations.

    The version of the OpenAPI document: v0.1
    Contact: felix@twenty.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from twentycrm_client.models.delete_one_attachment200_response_data import DeleteOneAttachment200ResponseData

class TestDeleteOneAttachment200ResponseData(unittest.TestCase):
    """DeleteOneAttachment200ResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeleteOneAttachment200ResponseData:
        """Test DeleteOneAttachment200ResponseData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeleteOneAttachment200ResponseData`
        """
        model = DeleteOneAttachment200ResponseData()
        if include_optional:
            return DeleteOneAttachment200ResponseData(
                delete_attachment = twentycrm_client.models.delete_many_attachments_200_response_data_delete_attachments_inner.deleteManyAttachments_200_response_data_deleteAttachments_inner(
                    id = '', )
            )
        else:
            return DeleteOneAttachment200ResponseData(
        )
        """

    def testDeleteOneAttachment200ResponseData(self):
        """Test DeleteOneAttachment200ResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
