# coding: utf-8

"""
    Twenty Api

    Twenty is a customer relationship management (CRM) platform designed to help businesses manage their customer interactions and relationships effectively. The Twenty API provides programmatic access to the features and functionalities of the Twenty CRM platform, allowing developers to integrate and interact with the CRM data and operations.

    The version of the OpenAPI document: v0.1
    Contact: felix@twenty.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from twentycrm_client.models.delete_one_message_channel200_response import DeleteOneMessageChannel200Response

class TestDeleteOneMessageChannel200Response(unittest.TestCase):
    """DeleteOneMessageChannel200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeleteOneMessageChannel200Response:
        """Test DeleteOneMessageChannel200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeleteOneMessageChannel200Response`
        """
        model = DeleteOneMessageChannel200Response()
        if include_optional:
            return DeleteOneMessageChannel200Response(
                data = twentycrm_client.models.delete_one_message_channel_200_response_data.deleteOneMessageChannel_200_response_data(
                    delete_message_channel = twentycrm_client.models.delete_many_attachments_200_response_data_delete_attachments_inner.deleteManyAttachments_200_response_data_deleteAttachments_inner(
                        id = '', ), )
            )
        else:
            return DeleteOneMessageChannel200Response(
        )
        """

    def testDeleteOneMessageChannel200Response(self):
        """Test DeleteOneMessageChannel200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
