# coding: utf-8

"""
    Twenty Api

    Twenty is a customer relationship management (CRM) platform designed to help businesses manage their customer interactions and relationships effectively. The Twenty API provides programmatic access to the features and functionalities of the Twenty CRM platform, allowing developers to integrate and interact with the CRM data and operations.

    The version of the OpenAPI document: v0.1
    Contact: felix@twenty.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from twentycrm_client.api.workflows_api import WorkflowsApi


class TestWorkflowsApi(unittest.TestCase):
    """WorkflowsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WorkflowsApi()

    def tearDown(self) -> None:
        pass

    def test_create_many_workflows(self) -> None:
        """Test case for create_many_workflows

        Create Many workflows
        """
        pass

    def test_create_one_workflow(self) -> None:
        """Test case for create_one_workflow

        Create One workflow
        """
        pass

    def test_delete_many_workflows(self) -> None:
        """Test case for delete_many_workflows

        Delete Many workflows
        """
        pass

    def test_delete_one_workflow(self) -> None:
        """Test case for delete_one_workflow

        Delete One workflow
        """
        pass

    def test_find_many_workflows(self) -> None:
        """Test case for find_many_workflows

        Find Many workflows
        """
        pass

    def test_find_one_workflow(self) -> None:
        """Test case for find_one_workflow

        Find One workflow
        """
        pass

    def test_find_workflow_duplicates(self) -> None:
        """Test case for find_workflow_duplicates

        Find workflow Duplicates
        """
        pass

    def test_group_by_workflows(self) -> None:
        """Test case for group_by_workflows

        Group By workflows
        """
        pass

    def test_merge_many_workflows(self) -> None:
        """Test case for merge_many_workflows

        Merge Many workflows
        """
        pass

    def test_restore_many_workflows(self) -> None:
        """Test case for restore_many_workflows

        Restore Many workflows
        """
        pass

    def test_restore_one_workflow(self) -> None:
        """Test case for restore_one_workflow

        Restore One workflow
        """
        pass

    def test_update_many_workflows(self) -> None:
        """Test case for update_many_workflows

        Update Many workflows
        """
        pass

    def test_update_one_workflow(self) -> None:
        """Test case for update_one_workflow

        Update One workflow
        """
        pass


if __name__ == '__main__':
    unittest.main()
