# coding: utf-8

"""
    Twenty Api

    Twenty is a customer relationship management (CRM) platform designed to help businesses manage their customer interactions and relationships effectively. The Twenty API provides programmatic access to the features and functionalities of the Twenty CRM platform, allowing developers to integrate and interact with the CRM data and operations.

    The version of the OpenAPI document: v0.1
    Contact: felix@twenty.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from twentycrm_client.api.calendar_channels_api import CalendarChannelsApi


class TestCalendarChannelsApi(unittest.TestCase):
    """CalendarChannelsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CalendarChannelsApi()

    def tearDown(self) -> None:
        pass

    def test_create_many_calendar_channels(self) -> None:
        """Test case for create_many_calendar_channels

        Create Many calendarChannels
        """
        pass

    def test_create_one_calendar_channel(self) -> None:
        """Test case for create_one_calendar_channel

        Create One calendarChannel
        """
        pass

    def test_delete_many_calendar_channels(self) -> None:
        """Test case for delete_many_calendar_channels

        Delete Many calendarChannels
        """
        pass

    def test_delete_one_calendar_channel(self) -> None:
        """Test case for delete_one_calendar_channel

        Delete One calendarChannel
        """
        pass

    def test_find_calendar_channel_duplicates(self) -> None:
        """Test case for find_calendar_channel_duplicates

        Find calendarChannel Duplicates
        """
        pass

    def test_find_many_calendar_channels(self) -> None:
        """Test case for find_many_calendar_channels

        Find Many calendarChannels
        """
        pass

    def test_find_one_calendar_channel(self) -> None:
        """Test case for find_one_calendar_channel

        Find One calendarChannel
        """
        pass

    def test_group_by_calendar_channels(self) -> None:
        """Test case for group_by_calendar_channels

        Group By calendarChannels
        """
        pass

    def test_merge_many_calendar_channels(self) -> None:
        """Test case for merge_many_calendar_channels

        Merge Many calendarChannels
        """
        pass

    def test_restore_many_calendar_channels(self) -> None:
        """Test case for restore_many_calendar_channels

        Restore Many calendarChannels
        """
        pass

    def test_restore_one_calendar_channel(self) -> None:
        """Test case for restore_one_calendar_channel

        Restore One calendarChannel
        """
        pass

    def test_update_many_calendar_channels(self) -> None:
        """Test case for update_many_calendar_channels

        Update Many calendarChannels
        """
        pass

    def test_update_one_calendar_channel(self) -> None:
        """Test case for update_one_calendar_channel

        Update One calendarChannel
        """
        pass


if __name__ == '__main__':
    unittest.main()
