# coding: utf-8

"""
    Twenty Api

    Twenty is a customer relationship management (CRM) platform designed to help businesses manage their customer interactions and relationships effectively. The Twenty API provides programmatic access to the features and functionalities of the Twenty CRM platform, allowing developers to integrate and interact with the CRM data and operations.

    The version of the OpenAPI document: v0.1
    Contact: felix@twenty.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from twentycrm_client.models.calendar_event_conference_link import CalendarEventConferenceLink
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CalendarEvent(BaseModel):
    """
    Calendar events
    """ # noqa: E501
    title: Optional[StrictStr] = Field(default=None, description="Title")
    is_canceled: Optional[StrictBool] = Field(default=None, description="Is canceled", alias="isCanceled")
    is_full_day: Optional[StrictBool] = Field(default=None, description="Is Full Day", alias="isFullDay")
    starts_at: Optional[datetime] = Field(default=None, description="Start Date", alias="startsAt")
    ends_at: Optional[datetime] = Field(default=None, description="End Date", alias="endsAt")
    external_created_at: Optional[datetime] = Field(default=None, description="Creation DateTime", alias="externalCreatedAt")
    external_updated_at: Optional[datetime] = Field(default=None, description="Update DateTime", alias="externalUpdatedAt")
    description: Optional[StrictStr] = Field(default=None, description="Description")
    location: Optional[StrictStr] = Field(default=None, description="Location")
    i_cal_uid: Optional[StrictStr] = Field(default=None, description="iCal UID", alias="iCalUid")
    conference_solution: Optional[StrictStr] = Field(default=None, description="Conference Solution", alias="conferenceSolution")
    conference_link: Optional[CalendarEventConferenceLink] = Field(default=None, alias="conferenceLink")
    __properties: ClassVar[List[str]] = ["title", "isCanceled", "isFullDay", "startsAt", "endsAt", "externalCreatedAt", "externalUpdatedAt", "description", "location", "iCalUid", "conferenceSolution", "conferenceLink"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CalendarEvent from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of conference_link
        if self.conference_link:
            _dict['conferenceLink'] = self.conference_link.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CalendarEvent from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "title": obj.get("title"),
            "isCanceled": obj.get("isCanceled"),
            "isFullDay": obj.get("isFullDay"),
            "startsAt": obj.get("startsAt"),
            "endsAt": obj.get("endsAt"),
            "externalCreatedAt": obj.get("externalCreatedAt"),
            "externalUpdatedAt": obj.get("externalUpdatedAt"),
            "description": obj.get("description"),
            "location": obj.get("location"),
            "iCalUid": obj.get("iCalUid"),
            "conferenceSolution": obj.get("conferenceSolution"),
            "conferenceLink": CalendarEventConferenceLink.from_dict(obj["conferenceLink"]) if obj.get("conferenceLink") is not None else None
        })
        return _obj


