# coding: utf-8

"""
    Twenty Api

    Twenty is a customer relationship management (CRM) platform designed to help businesses manage their customer interactions and relationships effectively. The Twenty API provides programmatic access to the features and functionalities of the Twenty CRM platform, allowing developers to integrate and interact with the CRM data and operations.

    The version of the OpenAPI document: v0.1
    Contact: felix@twenty.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from twentycrm_client.models.calendar_event_conference_link import CalendarEventConferenceLink
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CalendarEventForResponse(BaseModel):
    """
    Calendar events
    """ # noqa: E501
    title: Optional[StrictStr] = Field(default=None, description="Title")
    id: Optional[UUID] = Field(default=None, description="Id")
    created_at: Optional[datetime] = Field(default=None, description="Creation date", alias="createdAt")
    updated_at: Optional[datetime] = Field(default=None, description="Last time the record was changed", alias="updatedAt")
    deleted_at: Optional[datetime] = Field(default=None, description="Date when the record was deleted", alias="deletedAt")
    is_canceled: Optional[StrictBool] = Field(default=None, description="Is canceled", alias="isCanceled")
    is_full_day: Optional[StrictBool] = Field(default=None, description="Is Full Day", alias="isFullDay")
    starts_at: Optional[datetime] = Field(default=None, description="Start Date", alias="startsAt")
    ends_at: Optional[datetime] = Field(default=None, description="End Date", alias="endsAt")
    external_created_at: Optional[datetime] = Field(default=None, description="Creation DateTime", alias="externalCreatedAt")
    external_updated_at: Optional[datetime] = Field(default=None, description="Update DateTime", alias="externalUpdatedAt")
    description: Optional[StrictStr] = Field(default=None, description="Description")
    location: Optional[StrictStr] = Field(default=None, description="Location")
    i_cal_uid: Optional[StrictStr] = Field(default=None, description="iCal UID", alias="iCalUid")
    conference_solution: Optional[StrictStr] = Field(default=None, description="Conference Solution", alias="conferenceSolution")
    conference_link: Optional[CalendarEventConferenceLink] = Field(default=None, alias="conferenceLink")
    calendar_channel_event_associations: Optional[List[CalendarChannelEventAssociationForResponse]] = Field(default=None, description="Calendar Channel Event Associations", alias="calendarChannelEventAssociations")
    calendar_event_participants: Optional[List[CalendarEventParticipantForResponse]] = Field(default=None, description="Event Participants", alias="calendarEventParticipants")
    __properties: ClassVar[List[str]] = ["title", "id", "createdAt", "updatedAt", "deletedAt", "isCanceled", "isFullDay", "startsAt", "endsAt", "externalCreatedAt", "externalUpdatedAt", "description", "location", "iCalUid", "conferenceSolution", "conferenceLink", "calendarChannelEventAssociations", "calendarEventParticipants"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CalendarEventForResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of conference_link
        if self.conference_link:
            _dict['conferenceLink'] = self.conference_link.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in calendar_channel_event_associations (list)
        _items = []
        if self.calendar_channel_event_associations:
            for _item_calendar_channel_event_associations in self.calendar_channel_event_associations:
                if _item_calendar_channel_event_associations:
                    _items.append(_item_calendar_channel_event_associations.to_dict())
            _dict['calendarChannelEventAssociations'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in calendar_event_participants (list)
        _items = []
        if self.calendar_event_participants:
            for _item_calendar_event_participants in self.calendar_event_participants:
                if _item_calendar_event_participants:
                    _items.append(_item_calendar_event_participants.to_dict())
            _dict['calendarEventParticipants'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CalendarEventForResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "title": obj.get("title"),
            "id": obj.get("id"),
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt"),
            "deletedAt": obj.get("deletedAt"),
            "isCanceled": obj.get("isCanceled"),
            "isFullDay": obj.get("isFullDay"),
            "startsAt": obj.get("startsAt"),
            "endsAt": obj.get("endsAt"),
            "externalCreatedAt": obj.get("externalCreatedAt"),
            "externalUpdatedAt": obj.get("externalUpdatedAt"),
            "description": obj.get("description"),
            "location": obj.get("location"),
            "iCalUid": obj.get("iCalUid"),
            "conferenceSolution": obj.get("conferenceSolution"),
            "conferenceLink": CalendarEventConferenceLink.from_dict(obj["conferenceLink"]) if obj.get("conferenceLink") is not None else None,
            "calendarChannelEventAssociations": [CalendarChannelEventAssociationForResponse.from_dict(_item) for _item in obj["calendarChannelEventAssociations"]] if obj.get("calendarChannelEventAssociations") is not None else None,
            "calendarEventParticipants": [CalendarEventParticipantForResponse.from_dict(_item) for _item in obj["calendarEventParticipants"]] if obj.get("calendarEventParticipants") is not None else None
        })
        return _obj

from twentycrm_client.models.calendar_channel_event_association_for_response import CalendarChannelEventAssociationForResponse
from twentycrm_client.models.calendar_event_participant_for_response import CalendarEventParticipantForResponse
# TODO: Rewrite to not use raise_errors
CalendarEventForResponse.model_rebuild(raise_errors=False)

