# coding: utf-8

"""
    Twenty Api

    Twenty is a customer relationship management (CRM) platform designed to help businesses manage their customer interactions and relationships effectively. The Twenty API provides programmatic access to the features and functionalities of the Twenty CRM platform, allowing developers to integrate and interact with the CRM data and operations.

    The version of the OpenAPI document: v0.1
    Contact: felix@twenty.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CalendarChannelForResponse(BaseModel):
    """
    Calendar Channels
    """ # noqa: E501
    id: Optional[UUID] = Field(default=None, description="Id")
    created_at: Optional[datetime] = Field(default=None, description="Creation date", alias="createdAt")
    updated_at: Optional[datetime] = Field(default=None, description="Last time the record was changed", alias="updatedAt")
    deleted_at: Optional[datetime] = Field(default=None, description="Date when the record was deleted", alias="deletedAt")
    handle: Optional[StrictStr] = Field(default=None, description="Handle")
    visibility: Optional[StrictStr] = Field(default=None, description="Visibility")
    is_contact_auto_creation_enabled: Optional[StrictBool] = Field(default=None, description="Is Contact Auto Creation Enabled", alias="isContactAutoCreationEnabled")
    contact_auto_creation_policy: Optional[StrictStr] = Field(default=None, description="Automatically create records for people you participated with in an event.", alias="contactAutoCreationPolicy")
    is_sync_enabled: Optional[StrictBool] = Field(default=None, description="Is Sync Enabled", alias="isSyncEnabled")
    sync_cursor: Optional[StrictStr] = Field(default=None, description="Sync Cursor. Used for syncing events from the calendar provider", alias="syncCursor")
    sync_status: Optional[StrictStr] = Field(default=None, description="Sync status", alias="syncStatus")
    sync_stage: Optional[StrictStr] = Field(default=None, description="Sync stage", alias="syncStage")
    sync_stage_started_at: Optional[datetime] = Field(default=None, description="Sync stage started at", alias="syncStageStartedAt")
    synced_at: Optional[datetime] = Field(default=None, description="Last sync date", alias="syncedAt")
    throttle_failure_count: Optional[StrictInt] = Field(default=None, description="Throttle Failure Count", alias="throttleFailureCount")
    connected_account_id: Optional[UUID] = Field(default=None, alias="connectedAccountId")
    calendar_channel_event_associations: Optional[List[CalendarChannelEventAssociationForResponse]] = Field(default=None, description="Calendar Channel Event Associations", alias="calendarChannelEventAssociations")
    connected_account: Optional[ConnectedAccountForResponse] = Field(default=None, alias="connectedAccount")
    __properties: ClassVar[List[str]] = ["id", "createdAt", "updatedAt", "deletedAt", "handle", "visibility", "isContactAutoCreationEnabled", "contactAutoCreationPolicy", "isSyncEnabled", "syncCursor", "syncStatus", "syncStage", "syncStageStartedAt", "syncedAt", "throttleFailureCount", "connectedAccountId", "calendarChannelEventAssociations", "connectedAccount"]

    @field_validator('visibility')
    def visibility_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['METADATA', 'SHARE_EVERYTHING']):
            raise ValueError("must be one of enum values ('METADATA', 'SHARE_EVERYTHING')")
        return value

    @field_validator('contact_auto_creation_policy')
    def contact_auto_creation_policy_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['AS_PARTICIPANT_AND_ORGANIZER', 'AS_PARTICIPANT', 'AS_ORGANIZER', 'NONE']):
            raise ValueError("must be one of enum values ('AS_PARTICIPANT_AND_ORGANIZER', 'AS_PARTICIPANT', 'AS_ORGANIZER', 'NONE')")
        return value

    @field_validator('sync_status')
    def sync_status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['ONGOING', 'NOT_SYNCED', 'ACTIVE', 'FAILED_INSUFFICIENT_PERMISSIONS', 'FAILED_UNKNOWN']):
            raise ValueError("must be one of enum values ('ONGOING', 'NOT_SYNCED', 'ACTIVE', 'FAILED_INSUFFICIENT_PERMISSIONS', 'FAILED_UNKNOWN')")
        return value

    @field_validator('sync_stage')
    def sync_stage_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['CALENDAR_EVENT_LIST_FETCH_PENDING', 'CALENDAR_EVENT_LIST_FETCH_SCHEDULED', 'CALENDAR_EVENT_LIST_FETCH_ONGOING', 'CALENDAR_EVENTS_IMPORT_PENDING', 'CALENDAR_EVENTS_IMPORT_SCHEDULED', 'CALENDAR_EVENTS_IMPORT_ONGOING', 'FAILED', 'PENDING_CONFIGURATION']):
            raise ValueError("must be one of enum values ('CALENDAR_EVENT_LIST_FETCH_PENDING', 'CALENDAR_EVENT_LIST_FETCH_SCHEDULED', 'CALENDAR_EVENT_LIST_FETCH_ONGOING', 'CALENDAR_EVENTS_IMPORT_PENDING', 'CALENDAR_EVENTS_IMPORT_SCHEDULED', 'CALENDAR_EVENTS_IMPORT_ONGOING', 'FAILED', 'PENDING_CONFIGURATION')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CalendarChannelForResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in calendar_channel_event_associations (list)
        _items = []
        if self.calendar_channel_event_associations:
            for _item_calendar_channel_event_associations in self.calendar_channel_event_associations:
                if _item_calendar_channel_event_associations:
                    _items.append(_item_calendar_channel_event_associations.to_dict())
            _dict['calendarChannelEventAssociations'] = _items
        # override the default output from pydantic by calling `to_dict()` of connected_account
        if self.connected_account:
            _dict['connectedAccount'] = self.connected_account.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CalendarChannelForResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt"),
            "deletedAt": obj.get("deletedAt"),
            "handle": obj.get("handle"),
            "visibility": obj.get("visibility"),
            "isContactAutoCreationEnabled": obj.get("isContactAutoCreationEnabled"),
            "contactAutoCreationPolicy": obj.get("contactAutoCreationPolicy"),
            "isSyncEnabled": obj.get("isSyncEnabled"),
            "syncCursor": obj.get("syncCursor"),
            "syncStatus": obj.get("syncStatus"),
            "syncStage": obj.get("syncStage"),
            "syncStageStartedAt": obj.get("syncStageStartedAt"),
            "syncedAt": obj.get("syncedAt"),
            "throttleFailureCount": obj.get("throttleFailureCount"),
            "connectedAccountId": obj.get("connectedAccountId"),
            "calendarChannelEventAssociations": [CalendarChannelEventAssociationForResponse.from_dict(_item) for _item in obj["calendarChannelEventAssociations"]] if obj.get("calendarChannelEventAssociations") is not None else None,
            "connectedAccount": ConnectedAccountForResponse.from_dict(obj["connectedAccount"]) if obj.get("connectedAccount") is not None else None
        })
        return _obj

from twentycrm_client.models.calendar_channel_event_association_for_response import CalendarChannelEventAssociationForResponse
from twentycrm_client.models.connected_account_for_response import ConnectedAccountForResponse
# TODO: Rewrite to not use raise_errors
CalendarChannelForResponse.model_rebuild(raise_errors=False)

