# coding: utf-8

"""
    Twenty Api

    Twenty is a customer relationship management (CRM) platform designed to help businesses manage their customer interactions and relationships effectively. The Twenty API provides programmatic access to the features and functionalities of the Twenty CRM platform, allowing developers to integrate and interact with the CRM data and operations.

    The version of the OpenAPI document: v0.1
    Contact: felix@twenty.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from twentycrm_client.models.calendar_event_conference_link_secondary_links_inner import CalendarEventConferenceLinkSecondaryLinksInner
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CompanyDomainName(BaseModel):
    """
    The company website URL. We use this url to fetch the company icon
    """ # noqa: E501
    primary_link_label: Optional[StrictStr] = Field(default=None, alias="primaryLinkLabel")
    primary_link_url: Optional[StrictStr] = Field(default=None, alias="primaryLinkUrl")
    secondary_links: Optional[List[CalendarEventConferenceLinkSecondaryLinksInner]] = Field(default=None, alias="secondaryLinks")
    __properties: ClassVar[List[str]] = ["primaryLinkLabel", "primaryLinkUrl", "secondaryLinks"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CompanyDomainName from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in secondary_links (list)
        _items = []
        if self.secondary_links:
            for _item_secondary_links in self.secondary_links:
                if _item_secondary_links:
                    _items.append(_item_secondary_links.to_dict())
            _dict['secondaryLinks'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CompanyDomainName from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "primaryLinkLabel": obj.get("primaryLinkLabel"),
            "primaryLinkUrl": obj.get("primaryLinkUrl"),
            "secondaryLinks": [CalendarEventConferenceLinkSecondaryLinksInner.from_dict(_item) for _item in obj["secondaryLinks"]] if obj.get("secondaryLinks") is not None else None
        })
        return _obj


