# coding: utf-8

"""
    Twenty Api

    Twenty is a customer relationship management (CRM) platform designed to help businesses manage their customer interactions and relationships effectively. The Twenty API provides programmatic access to the features and functionalities of the Twenty CRM platform, allowing developers to integrate and interact with the CRM data and operations.

    The version of the OpenAPI document: v0.1
    Contact: felix@twenty.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class FavoriteForUpdate(BaseModel):
    """
    A favorite
    """ # noqa: E501
    position: Optional[StrictInt] = Field(default=None, description="Favorite position")
    view_id: Optional[UUID] = Field(default=None, description="ViewId", alias="viewId")
    company_id: Optional[UUID] = Field(default=None, alias="companyId")
    dashboard_id: Optional[UUID] = Field(default=None, alias="dashboardId")
    for_workspace_member_id: Optional[UUID] = Field(default=None, alias="forWorkspaceMemberId")
    person_id: Optional[UUID] = Field(default=None, alias="personId")
    opportunity_id: Optional[UUID] = Field(default=None, alias="opportunityId")
    workflow_id: Optional[UUID] = Field(default=None, alias="workflowId")
    workflow_version_id: Optional[UUID] = Field(default=None, alias="workflowVersionId")
    workflow_run_id: Optional[UUID] = Field(default=None, alias="workflowRunId")
    task_id: Optional[UUID] = Field(default=None, alias="taskId")
    note_id: Optional[UUID] = Field(default=None, alias="noteId")
    favorite_folder_id: Optional[UUID] = Field(default=None, alias="favoriteFolderId")
    __properties: ClassVar[List[str]] = ["position", "viewId", "companyId", "dashboardId", "forWorkspaceMemberId", "personId", "opportunityId", "workflowId", "workflowVersionId", "workflowRunId", "taskId", "noteId", "favoriteFolderId"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FavoriteForUpdate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FavoriteForUpdate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "position": obj.get("position"),
            "viewId": obj.get("viewId"),
            "companyId": obj.get("companyId"),
            "dashboardId": obj.get("dashboardId"),
            "forWorkspaceMemberId": obj.get("forWorkspaceMemberId"),
            "personId": obj.get("personId"),
            "opportunityId": obj.get("opportunityId"),
            "workflowId": obj.get("workflowId"),
            "workflowVersionId": obj.get("workflowVersionId"),
            "workflowRunId": obj.get("workflowRunId"),
            "taskId": obj.get("taskId"),
            "noteId": obj.get("noteId"),
            "favoriteFolderId": obj.get("favoriteFolderId")
        })
        return _obj


