# coding: utf-8

"""
    Twenty Api

    Twenty is a customer relationship management (CRM) platform designed to help businesses manage their customer interactions and relationships effectively. The Twenty API provides programmatic access to the features and functionalities of the Twenty CRM platform, allowing developers to integrate and interact with the CRM data and operations.

    The version of the OpenAPI document: v0.1
    Contact: felix@twenty.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from twentycrm_client.models.get_open_api_schema200_response_components import GetOpenApiSchema200ResponseComponents
from twentycrm_client.models.get_open_api_schema200_response_info import GetOpenApiSchema200ResponseInfo
from twentycrm_client.models.get_open_api_schema200_response_servers_inner import GetOpenApiSchema200ResponseServersInner
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class GetOpenApiSchema200Response(BaseModel):
    """
    GetOpenApiSchema200Response
    """ # noqa: E501
    openapi: Optional[StrictStr] = None
    info: Optional[GetOpenApiSchema200ResponseInfo] = None
    servers: Optional[List[GetOpenApiSchema200ResponseServersInner]] = None
    components: Optional[GetOpenApiSchema200ResponseComponents] = None
    paths: Optional[Dict[str, Any]] = None
    tags: Optional[Dict[str, Any]] = None
    __properties: ClassVar[List[str]] = ["openapi", "info", "servers", "components", "paths", "tags"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetOpenApiSchema200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of info
        if self.info:
            _dict['info'] = self.info.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in servers (list)
        _items = []
        if self.servers:
            for _item_servers in self.servers:
                if _item_servers:
                    _items.append(_item_servers.to_dict())
            _dict['servers'] = _items
        # override the default output from pydantic by calling `to_dict()` of components
        if self.components:
            _dict['components'] = self.components.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetOpenApiSchema200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "openapi": obj.get("openapi"),
            "info": GetOpenApiSchema200ResponseInfo.from_dict(obj["info"]) if obj.get("info") is not None else None,
            "servers": [GetOpenApiSchema200ResponseServersInner.from_dict(_item) for _item in obj["servers"]] if obj.get("servers") is not None else None,
            "components": GetOpenApiSchema200ResponseComponents.from_dict(obj["components"]) if obj.get("components") is not None else None,
            "paths": obj.get("paths"),
            "tags": obj.get("tags")
        })
        return _obj


