# coding: utf-8

"""
    Twenty Api

    Twenty is a customer relationship management (CRM) platform designed to help businesses manage their customer interactions and relationships effectively. The Twenty API provides programmatic access to the features and functionalities of the Twenty CRM platform, allowing developers to integrate and interact with the CRM data and operations.

    The version of the OpenAPI document: v0.1
    Contact: felix@twenty.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from twentycrm_client.models.group_by_message_threads200_response_data_message_threads_group_by_inner import GroupByMessageThreads200ResponseDataMessageThreadsGroupByInner
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class GroupByMessageThreads200ResponseData(BaseModel):
    """
    GroupByMessageThreads200ResponseData
    """ # noqa: E501
    message_threads_group_by: Optional[List[GroupByMessageThreads200ResponseDataMessageThreadsGroupByInner]] = Field(default=None, alias="messageThreadsGroupBy")
    __properties: ClassVar[List[str]] = ["messageThreadsGroupBy"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GroupByMessageThreads200ResponseData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in message_threads_group_by (list)
        _items = []
        if self.message_threads_group_by:
            for _item_message_threads_group_by in self.message_threads_group_by:
                if _item_message_threads_group_by:
                    _items.append(_item_message_threads_group_by.to_dict())
            _dict['messageThreadsGroupBy'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GroupByMessageThreads200ResponseData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "messageThreadsGroupBy": [GroupByMessageThreads200ResponseDataMessageThreadsGroupByInner.from_dict(_item) for _item in obj["messageThreadsGroupBy"]] if obj.get("messageThreadsGroupBy") is not None else None
        })
        return _obj


