# coding: utf-8

"""
    Twenty Api

    Twenty is a customer relationship management (CRM) platform designed to help businesses manage their customer interactions and relationships effectively. The Twenty API provides programmatic access to the features and functionalities of the Twenty CRM platform, allowing developers to integrate and interact with the CRM data and operations.

    The version of the OpenAPI document: v0.1
    Contact: felix@twenty.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class MessageThreadForResponse(BaseModel):
    """
    Message Thread
    """ # noqa: E501
    id: Optional[UUID] = Field(default=None, description="Id")
    created_at: Optional[datetime] = Field(default=None, description="Creation date", alias="createdAt")
    updated_at: Optional[datetime] = Field(default=None, description="Last time the record was changed", alias="updatedAt")
    deleted_at: Optional[datetime] = Field(default=None, description="Date when the record was deleted", alias="deletedAt")
    messages: Optional[List[MessageForResponse]] = Field(default=None, description="Messages from the thread.")
    message_channel_message_associations: Optional[List[MessageChannelMessageAssociationForResponse]] = Field(default=None, description="Messages from the channel.", alias="messageChannelMessageAssociations")
    __properties: ClassVar[List[str]] = ["id", "createdAt", "updatedAt", "deletedAt", "messages", "messageChannelMessageAssociations"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MessageThreadForResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in messages (list)
        _items = []
        if self.messages:
            for _item_messages in self.messages:
                if _item_messages:
                    _items.append(_item_messages.to_dict())
            _dict['messages'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in message_channel_message_associations (list)
        _items = []
        if self.message_channel_message_associations:
            for _item_message_channel_message_associations in self.message_channel_message_associations:
                if _item_message_channel_message_associations:
                    _items.append(_item_message_channel_message_associations.to_dict())
            _dict['messageChannelMessageAssociations'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MessageThreadForResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt"),
            "deletedAt": obj.get("deletedAt"),
            "messages": [MessageForResponse.from_dict(_item) for _item in obj["messages"]] if obj.get("messages") is not None else None,
            "messageChannelMessageAssociations": [MessageChannelMessageAssociationForResponse.from_dict(_item) for _item in obj["messageChannelMessageAssociations"]] if obj.get("messageChannelMessageAssociations") is not None else None
        })
        return _obj

from twentycrm_client.models.message_channel_message_association_for_response import MessageChannelMessageAssociationForResponse
from twentycrm_client.models.message_for_response import MessageForResponse
# TODO: Rewrite to not use raise_errors
MessageThreadForResponse.model_rebuild(raise_errors=False)

