# coding: utf-8

"""
    Twenty Api

    Twenty is a customer relationship management (CRM) platform designed to help businesses manage their customer interactions and relationships effectively. The Twenty API provides programmatic access to the features and functionalities of the Twenty CRM platform, allowing developers to integrate and interact with the CRM data and operations.

    The version of the OpenAPI document: v0.1
    Contact: felix@twenty.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class MessageChannelMessageAssociationForResponse(BaseModel):
    """
    Message Synced with a Message Channel
    """ # noqa: E501
    id: Optional[UUID] = Field(default=None, description="Id")
    created_at: Optional[datetime] = Field(default=None, description="Creation date", alias="createdAt")
    updated_at: Optional[datetime] = Field(default=None, description="Last time the record was changed", alias="updatedAt")
    deleted_at: Optional[datetime] = Field(default=None, description="Date when the record was deleted", alias="deletedAt")
    message_external_id: Optional[StrictStr] = Field(default=None, description="Message id from the messaging provider", alias="messageExternalId")
    message_thread_external_id: Optional[StrictStr] = Field(default=None, description="Thread id from the messaging provider", alias="messageThreadExternalId")
    direction: Optional[StrictStr] = Field(default=None, description="Message Direction")
    message_id: Optional[UUID] = Field(default=None, alias="messageId")
    message_channel_id: Optional[UUID] = Field(default=None, alias="messageChannelId")
    message_thread_id: Optional[UUID] = Field(default=None, alias="messageThreadId")
    message: Optional[MessageForResponse] = None
    message_channel: Optional[MessageChannelForResponse] = Field(default=None, alias="messageChannel")
    message_thread: Optional[MessageThreadForResponse] = Field(default=None, alias="messageThread")
    __properties: ClassVar[List[str]] = ["id", "createdAt", "updatedAt", "deletedAt", "messageExternalId", "messageThreadExternalId", "direction", "messageId", "messageChannelId", "messageThreadId", "message", "messageChannel", "messageThread"]

    @field_validator('direction')
    def direction_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['INCOMING', 'OUTGOING']):
            raise ValueError("must be one of enum values ('INCOMING', 'OUTGOING')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MessageChannelMessageAssociationForResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of message
        if self.message:
            _dict['message'] = self.message.to_dict()
        # override the default output from pydantic by calling `to_dict()` of message_channel
        if self.message_channel:
            _dict['messageChannel'] = self.message_channel.to_dict()
        # override the default output from pydantic by calling `to_dict()` of message_thread
        if self.message_thread:
            _dict['messageThread'] = self.message_thread.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MessageChannelMessageAssociationForResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt"),
            "deletedAt": obj.get("deletedAt"),
            "messageExternalId": obj.get("messageExternalId"),
            "messageThreadExternalId": obj.get("messageThreadExternalId"),
            "direction": obj.get("direction"),
            "messageId": obj.get("messageId"),
            "messageChannelId": obj.get("messageChannelId"),
            "messageThreadId": obj.get("messageThreadId"),
            "message": MessageForResponse.from_dict(obj["message"]) if obj.get("message") is not None else None,
            "messageChannel": MessageChannelForResponse.from_dict(obj["messageChannel"]) if obj.get("messageChannel") is not None else None,
            "messageThread": MessageThreadForResponse.from_dict(obj["messageThread"]) if obj.get("messageThread") is not None else None
        })
        return _obj

from twentycrm_client.models.message_channel_for_response import MessageChannelForResponse
from twentycrm_client.models.message_for_response import MessageForResponse
from twentycrm_client.models.message_thread_for_response import MessageThreadForResponse
# TODO: Rewrite to not use raise_errors
MessageChannelMessageAssociationForResponse.model_rebuild(raise_errors=False)

