# coding: utf-8

"""
    Twenty Api

    Twenty is a customer relationship management (CRM) platform designed to help businesses manage their customer interactions and relationships effectively. The Twenty API provides programmatic access to the features and functionalities of the Twenty CRM platform, allowing developers to integrate and interact with the CRM data and operations.

    The version of the OpenAPI document: v0.1
    Contact: felix@twenty.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from uuid import UUID
from twentycrm_client.models.attachment_created_by import AttachmentCreatedBy
from twentycrm_client.models.attachment_updated_by import AttachmentUpdatedBy
from twentycrm_client.models.opportunity_amount import OpportunityAmount
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class OpportunityForUpdate(BaseModel):
    """
    An opportunity
    """ # noqa: E501
    name: Optional[StrictStr] = Field(default=None, description="The opportunity name")
    amount: Optional[OpportunityAmount] = None
    close_date: Optional[datetime] = Field(default=None, description="Opportunity close date", alias="closeDate")
    stage: Optional[StrictStr] = Field(default=None, description="Opportunity stage")
    position: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Opportunity record position")
    created_by: Optional[AttachmentCreatedBy] = Field(default=None, alias="createdBy")
    updated_by: Optional[AttachmentUpdatedBy] = Field(default=None, alias="updatedBy")
    company_id: Optional[UUID] = Field(default=None, alias="companyId")
    point_of_contact_id: Optional[UUID] = Field(default=None, alias="pointOfContactId")
    owner_id: Optional[UUID] = Field(default=None, alias="ownerId")
    __properties: ClassVar[List[str]] = ["name", "amount", "closeDate", "stage", "position", "createdBy", "updatedBy", "companyId", "pointOfContactId", "ownerId"]

    @field_validator('stage')
    def stage_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['NEW', 'SCREENING', 'MEETING', 'PROPOSAL', 'CUSTOMER']):
            raise ValueError("must be one of enum values ('NEW', 'SCREENING', 'MEETING', 'PROPOSAL', 'CUSTOMER')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OpportunityForUpdate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of amount
        if self.amount:
            _dict['amount'] = self.amount.to_dict()
        # override the default output from pydantic by calling `to_dict()` of created_by
        if self.created_by:
            _dict['createdBy'] = self.created_by.to_dict()
        # override the default output from pydantic by calling `to_dict()` of updated_by
        if self.updated_by:
            _dict['updatedBy'] = self.updated_by.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OpportunityForUpdate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "amount": OpportunityAmount.from_dict(obj["amount"]) if obj.get("amount") is not None else None,
            "closeDate": obj.get("closeDate"),
            "stage": obj.get("stage"),
            "position": obj.get("position"),
            "createdBy": AttachmentCreatedBy.from_dict(obj["createdBy"]) if obj.get("createdBy") is not None else None,
            "updatedBy": AttachmentUpdatedBy.from_dict(obj["updatedBy"]) if obj.get("updatedBy") is not None else None,
            "companyId": obj.get("companyId"),
            "pointOfContactId": obj.get("pointOfContactId"),
            "ownerId": obj.get("ownerId")
        })
        return _obj


