# coding: utf-8

"""
    Twenty Api

    Twenty is a customer relationship management (CRM) platform designed to help businesses manage their customer interactions and relationships effectively. The Twenty API provides programmatic access to the features and functionalities of the Twenty CRM platform, allowing developers to integrate and interact with the CRM data and operations.

    The version of the OpenAPI document: v0.1
    Contact: felix@twenty.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class TimelineActivityForResponse(BaseModel):
    """
    Aggregated / filtered event to be displayed on the timeline
    """ # noqa: E501
    id: Optional[UUID] = Field(default=None, description="Id")
    created_at: Optional[datetime] = Field(default=None, description="Creation date", alias="createdAt")
    updated_at: Optional[datetime] = Field(default=None, description="Last time the record was changed", alias="updatedAt")
    deleted_at: Optional[datetime] = Field(default=None, description="Date when the record was deleted", alias="deletedAt")
    happens_at: Optional[datetime] = Field(default=None, description="Creation date", alias="happensAt")
    name: Optional[StrictStr] = Field(default=None, description="Event name")
    properties: Optional[Dict[str, Any]] = Field(default=None, description="Json value for event details")
    linked_record_cached_name: Optional[StrictStr] = Field(default=None, description="Cached record name", alias="linkedRecordCachedName")
    linked_record_id: Optional[UUID] = Field(default=None, description="Linked Record id", alias="linkedRecordId")
    linked_object_metadata_id: Optional[UUID] = Field(default=None, description="Linked Object Metadata Id", alias="linkedObjectMetadataId")
    target_company: Optional[StrictStr] = Field(default=None, description="Event target", alias="targetCompany")
    target_dashboard: Optional[StrictStr] = Field(default=None, description="Event target", alias="targetDashboard")
    target_note: Optional[StrictStr] = Field(default=None, description="Event target", alias="targetNote")
    target_opportunity: Optional[StrictStr] = Field(default=None, description="Event target", alias="targetOpportunity")
    target_person: Optional[StrictStr] = Field(default=None, description="Event target", alias="targetPerson")
    target_task: Optional[StrictStr] = Field(default=None, description="Event target", alias="targetTask")
    workspace_member_id: Optional[UUID] = Field(default=None, alias="workspaceMemberId")
    target_workflow: Optional[StrictStr] = Field(default=None, description="Event target", alias="targetWorkflow")
    target_workflow_version: Optional[StrictStr] = Field(default=None, description="Event target", alias="targetWorkflowVersion")
    target_workflow_run: Optional[StrictStr] = Field(default=None, description="Event target", alias="targetWorkflowRun")
    workspace_member: Optional[WorkspaceMemberForResponse] = Field(default=None, alias="workspaceMember")
    __properties: ClassVar[List[str]] = ["id", "createdAt", "updatedAt", "deletedAt", "happensAt", "name", "properties", "linkedRecordCachedName", "linkedRecordId", "linkedObjectMetadataId", "targetCompany", "targetDashboard", "targetNote", "targetOpportunity", "targetPerson", "targetTask", "workspaceMemberId", "targetWorkflow", "targetWorkflowVersion", "targetWorkflowRun", "workspaceMember"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TimelineActivityForResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of workspace_member
        if self.workspace_member:
            _dict['workspaceMember'] = self.workspace_member.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TimelineActivityForResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt"),
            "deletedAt": obj.get("deletedAt"),
            "happensAt": obj.get("happensAt"),
            "name": obj.get("name"),
            "properties": obj.get("properties"),
            "linkedRecordCachedName": obj.get("linkedRecordCachedName"),
            "linkedRecordId": obj.get("linkedRecordId"),
            "linkedObjectMetadataId": obj.get("linkedObjectMetadataId"),
            "targetCompany": obj.get("targetCompany"),
            "targetDashboard": obj.get("targetDashboard"),
            "targetNote": obj.get("targetNote"),
            "targetOpportunity": obj.get("targetOpportunity"),
            "targetPerson": obj.get("targetPerson"),
            "targetTask": obj.get("targetTask"),
            "workspaceMemberId": obj.get("workspaceMemberId"),
            "targetWorkflow": obj.get("targetWorkflow"),
            "targetWorkflowVersion": obj.get("targetWorkflowVersion"),
            "targetWorkflowRun": obj.get("targetWorkflowRun"),
            "workspaceMember": WorkspaceMemberForResponse.from_dict(obj["workspaceMember"]) if obj.get("workspaceMember") is not None else None
        })
        return _obj

from twentycrm_client.models.workspace_member_for_response import WorkspaceMemberForResponse
# TODO: Rewrite to not use raise_errors
TimelineActivityForResponse.model_rebuild(raise_errors=False)

