# coding: utf-8

"""
    Twenty Api

    Twenty is a customer relationship management (CRM) platform designed to help businesses manage their customer interactions and relationships effectively. The Twenty API provides programmatic access to the features and functionalities of the Twenty CRM platform, allowing developers to integrate and interact with the CRM data and operations.

    The version of the OpenAPI document: v0.1
    Contact: felix@twenty.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from uuid import UUID
from twentycrm_client.models.attachment_for_response_updated_by import AttachmentForResponseUpdatedBy
from twentycrm_client.models.workflow_run_for_response_created_by import WorkflowRunForResponseCreatedBy
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class WorkflowRunForResponse(BaseModel):
    """
    A workflow run
    """ # noqa: E501
    id: Optional[UUID] = Field(default=None, description="Id")
    created_at: Optional[datetime] = Field(default=None, description="Creation date", alias="createdAt")
    updated_at: Optional[datetime] = Field(default=None, description="Last time the record was changed", alias="updatedAt")
    deleted_at: Optional[datetime] = Field(default=None, description="Date when the record was deleted", alias="deletedAt")
    name: Optional[StrictStr] = Field(default=None, description="Name of the workflow run")
    enqueued_at: Optional[datetime] = Field(default=None, description="Workflow run enqueued at", alias="enqueuedAt")
    started_at: Optional[datetime] = Field(default=None, description="Workflow run started at", alias="startedAt")
    ended_at: Optional[datetime] = Field(default=None, description="Workflow run ended at", alias="endedAt")
    status: Optional[StrictStr] = Field(default=None, description="Workflow run status")
    created_by: Optional[WorkflowRunForResponseCreatedBy] = Field(default=None, alias="createdBy")
    updated_by: Optional[AttachmentForResponseUpdatedBy] = Field(default=None, alias="updatedBy")
    state: Optional[Dict[str, Any]] = Field(default=None, description="State of the workflow run")
    context: Optional[Dict[str, Any]] = Field(default=None, description="Context of the workflow run")
    output: Optional[Dict[str, Any]] = Field(default=None, description="Output of the workflow run")
    position: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Workflow run position")
    workflow_id: Optional[UUID] = Field(default=None, alias="workflowId")
    workflow_version_id: Optional[UUID] = Field(default=None, alias="workflowVersionId")
    favorites: Optional[List[FavoriteForResponse]] = Field(default=None, description="Favorites linked to the workflow run")
    timeline_activities: Optional[List[TimelineActivityForResponse]] = Field(default=None, description="Timeline activities linked to the run", alias="timelineActivities")
    workflow: Optional[WorkflowForResponse] = None
    workflow_version: Optional[WorkflowVersionForResponse] = Field(default=None, alias="workflowVersion")
    __properties: ClassVar[List[str]] = ["id", "createdAt", "updatedAt", "deletedAt", "name", "enqueuedAt", "startedAt", "endedAt", "status", "createdBy", "updatedBy", "state", "context", "output", "position", "workflowId", "workflowVersionId", "favorites", "timelineActivities", "workflow", "workflowVersion"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['NOT_STARTED', 'RUNNING', 'COMPLETED', 'FAILED', 'ENQUEUED', 'STOPPING', 'STOPPED']):
            raise ValueError("must be one of enum values ('NOT_STARTED', 'RUNNING', 'COMPLETED', 'FAILED', 'ENQUEUED', 'STOPPING', 'STOPPED')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WorkflowRunForResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of created_by
        if self.created_by:
            _dict['createdBy'] = self.created_by.to_dict()
        # override the default output from pydantic by calling `to_dict()` of updated_by
        if self.updated_by:
            _dict['updatedBy'] = self.updated_by.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in favorites (list)
        _items = []
        if self.favorites:
            for _item_favorites in self.favorites:
                if _item_favorites:
                    _items.append(_item_favorites.to_dict())
            _dict['favorites'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in timeline_activities (list)
        _items = []
        if self.timeline_activities:
            for _item_timeline_activities in self.timeline_activities:
                if _item_timeline_activities:
                    _items.append(_item_timeline_activities.to_dict())
            _dict['timelineActivities'] = _items
        # override the default output from pydantic by calling `to_dict()` of workflow
        if self.workflow:
            _dict['workflow'] = self.workflow.to_dict()
        # override the default output from pydantic by calling `to_dict()` of workflow_version
        if self.workflow_version:
            _dict['workflowVersion'] = self.workflow_version.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WorkflowRunForResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt"),
            "deletedAt": obj.get("deletedAt"),
            "name": obj.get("name"),
            "enqueuedAt": obj.get("enqueuedAt"),
            "startedAt": obj.get("startedAt"),
            "endedAt": obj.get("endedAt"),
            "status": obj.get("status"),
            "createdBy": WorkflowRunForResponseCreatedBy.from_dict(obj["createdBy"]) if obj.get("createdBy") is not None else None,
            "updatedBy": AttachmentForResponseUpdatedBy.from_dict(obj["updatedBy"]) if obj.get("updatedBy") is not None else None,
            "state": obj.get("state"),
            "context": obj.get("context"),
            "output": obj.get("output"),
            "position": obj.get("position"),
            "workflowId": obj.get("workflowId"),
            "workflowVersionId": obj.get("workflowVersionId"),
            "favorites": [FavoriteForResponse.from_dict(_item) for _item in obj["favorites"]] if obj.get("favorites") is not None else None,
            "timelineActivities": [TimelineActivityForResponse.from_dict(_item) for _item in obj["timelineActivities"]] if obj.get("timelineActivities") is not None else None,
            "workflow": WorkflowForResponse.from_dict(obj["workflow"]) if obj.get("workflow") is not None else None,
            "workflowVersion": WorkflowVersionForResponse.from_dict(obj["workflowVersion"]) if obj.get("workflowVersion") is not None else None
        })
        return _obj

from twentycrm_client.models.favorite_for_response import FavoriteForResponse
from twentycrm_client.models.timeline_activity_for_response import TimelineActivityForResponse
from twentycrm_client.models.workflow_for_response import WorkflowForResponse
from twentycrm_client.models.workflow_version_for_response import WorkflowVersionForResponse
# TODO: Rewrite to not use raise_errors
WorkflowRunForResponse.model_rebuild(raise_errors=False)

