# coding: utf-8

"""
    Twenty Api

    Twenty is a customer relationship management (CRM) platform designed to help businesses manage their customer interactions and relationships effectively. The Twenty API provides programmatic access to the features and functionalities of the Twenty CRM platform, allowing developers to integrate and interact with the CRM data and operations.

    The version of the OpenAPI document: v0.1
    Contact: felix@twenty.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from uuid import UUID
from twentycrm_client.models.workspace_member_name import WorkspaceMemberName
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class WorkspaceMember(BaseModel):
    """
    A workspace member
    """ # noqa: E501
    position: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Workspace member position")
    name: WorkspaceMemberName
    color_scheme: Optional[StrictStr] = Field(default=None, description="Preferred color scheme", alias="colorScheme")
    locale: Optional[StrictStr] = Field(default=None, description="Preferred language")
    avatar_url: Optional[StrictStr] = Field(default=None, description="Workspace member avatar", alias="avatarUrl")
    user_email: Optional[StrictStr] = Field(default=None, description="Related user email address", alias="userEmail")
    calendar_start_day: Optional[StrictInt] = Field(default=None, description="User's preferred start day of the week", alias="calendarStartDay")
    user_id: UUID = Field(description="Associated User Id", alias="userId")
    time_zone: Optional[StrictStr] = Field(default=None, description="User time zone", alias="timeZone")
    date_format: Optional[StrictStr] = Field(default=None, description="User's preferred date format", alias="dateFormat")
    time_format: Optional[StrictStr] = Field(default=None, description="User's preferred time format", alias="timeFormat")
    number_format: Optional[StrictStr] = Field(default=None, description="User's preferred number format", alias="numberFormat")
    __properties: ClassVar[List[str]] = ["position", "name", "colorScheme", "locale", "avatarUrl", "userEmail", "calendarStartDay", "userId", "timeZone", "dateFormat", "timeFormat", "numberFormat"]

    @field_validator('date_format')
    def date_format_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['SYSTEM', 'MONTH_FIRST', 'DAY_FIRST', 'YEAR_FIRST']):
            raise ValueError("must be one of enum values ('SYSTEM', 'MONTH_FIRST', 'DAY_FIRST', 'YEAR_FIRST')")
        return value

    @field_validator('time_format')
    def time_format_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['SYSTEM', 'HOUR_24', 'HOUR_12']):
            raise ValueError("must be one of enum values ('SYSTEM', 'HOUR_24', 'HOUR_12')")
        return value

    @field_validator('number_format')
    def number_format_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['SYSTEM', 'COMMAS_AND_DOT', 'SPACES_AND_COMMA', 'DOTS_AND_COMMA', 'APOSTROPHE_AND_DOT']):
            raise ValueError("must be one of enum values ('SYSTEM', 'COMMAS_AND_DOT', 'SPACES_AND_COMMA', 'DOTS_AND_COMMA', 'APOSTROPHE_AND_DOT')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WorkspaceMember from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of name
        if self.name:
            _dict['name'] = self.name.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WorkspaceMember from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "position": obj.get("position"),
            "name": WorkspaceMemberName.from_dict(obj["name"]) if obj.get("name") is not None else None,
            "colorScheme": obj.get("colorScheme"),
            "locale": obj.get("locale"),
            "avatarUrl": obj.get("avatarUrl"),
            "userEmail": obj.get("userEmail"),
            "calendarStartDay": obj.get("calendarStartDay"),
            "userId": obj.get("userId"),
            "timeZone": obj.get("timeZone"),
            "dateFormat": obj.get("dateFormat"),
            "timeFormat": obj.get("timeFormat"),
            "numberFormat": obj.get("numberFormat")
        })
        return _obj


